import { mkdir, readFile } from "node:fs/promises";
import { createRequire } from "node:module";
import { dirname, join } from "node:path";
import { Context, Effect, Layer } from "effect";
import {
  AtomicFileWriterService,
  atomicFileWriterLayer,
} from "../../../providers/filesystem/atomic-file-writer";
import { RigPathsConfigService, rigPathsConfigLayer } from "../../../providers/paths/rig-paths";
import { RigError } from "../../../providers/errors/rig-error";
import { RuntimeTypesSource } from "../config/runtime-support-types-source";
import { RuntimeSupportSdkSourceTemplate } from "../config/runtime-support-sdk-source";

export class RuntimeSupportService extends Context.Service<
  RuntimeSupportService,
  { readonly ensure: (registryDirs?: string[]) => Effect.Effect<void, RigError> }
>()("@rendotdev/rig/generated/RuntimeSupportService", {
  make: Effect.gen(function* () {
    const paths = yield* RigPathsConfigService;
    const writer = yield* AtomicFileWriterService;
    const renderer = yield* RuntimeSupportRendererService;
    const toError = (cause: unknown): RigError =>
      cause instanceof RigError
        ? cause
        : new RigError({
            code: "INTERNAL_ERROR",
            message: cause instanceof Error ? cause.message : String(cause),
          });
    const readTextIfExists = async (path: string): Promise<string | undefined> => {
      try {
        return typeof Bun !== "undefined" && typeof Bun.file === "function"
          ? await Bun.file(path).text()
          : await readFile(path, "utf8");
      } catch {
        return undefined;
      }
    };
    const writeTextIfChanged = Effect.fn("RuntimeSupportService.writeTextIfChanged")(function* (
      path: string,
      content: string,
    ) {
      if ((yield* Effect.promise(() => readTextIfExists(path))) === content) return;
      yield* writer.write(path, content).pipe(Effect.mapError((error) => toError(error.cause)));
    });
    const ensureRegistryTsconfig = Effect.fn("RuntimeSupportService.ensureRegistryTsconfig")(
      function* (registryDir: string) {
        yield* Effect.tryPromise({
          try: () => mkdir(registryDir, { recursive: true }),
          catch: toError,
        });
        const tsconfigPath = join(registryDir, "tsconfig.json");
        const existing = yield* Effect.promise(() => readTextIfExists(tsconfigPath));
        const hasCustomTsconfig =
          existing !== undefined && !existing.startsWith("// Generated by Rig.");
        if (hasCustomTsconfig) return;
        yield* writeTextIfChanged(tsconfigPath, yield* renderer.registryTsconfig);
      },
    );
    const ensure = Effect.fn("RuntimeSupportService.ensure")(function* (
      registryDirs: string[] = [],
    ) {
      yield* Effect.tryPromise({
        try: () => mkdir(paths.runtimeDir, { recursive: true }),
        catch: toError,
      });
      yield* Effect.all([
        writeTextIfChanged(paths.runtimeSdkPath, yield* renderer.sdk),
        writeTextIfChanged(paths.runtimeTypesPath, RuntimeTypesSource),
        writeTextIfChanged(paths.runtimeGlobalsPath, yield* renderer.globals),
      ]);
      yield* Effect.all(registryDirs.map(ensureRegistryTsconfig), { concurrency: "unbounded" });
    });
    return { ensure } as const;
  }),
}) {
  static readonly layer = Layer.effect(RuntimeSupportService, RuntimeSupportService.make);
}

class RuntimeSupportSdkRendererService extends Context.Service<
  RuntimeSupportSdkRendererService,
  { readonly sdk: Effect.Effect<string> }
>()("@rendotdev/rig/generated/RuntimeSupportSdkRendererService", {
  make: Effect.gen(function* () {
    const resolveImport = (specifier: string): string => {
      const meta = import.meta as ImportMeta & { resolve?: (id: string) => string };
      return meta.resolve ? meta.resolve(specifier) : specifier;
    };
    const sdk = Effect.sync(() =>
      RuntimeSupportSdkSourceTemplate.replace(
        "__RIG_ZOD_IMPORT__",
        JSON.stringify(resolveImport("zod")),
      ),
    ).pipe(Effect.withSpan("RuntimeSupportSdkRendererService.sdk"));
    return { sdk } as const;
  }),
}) {
  static readonly layer = Layer.effect(
    RuntimeSupportSdkRendererService,
    RuntimeSupportSdkRendererService.make,
  );
}

class RuntimeSupportGlobalsRendererService extends Context.Service<
  RuntimeSupportGlobalsRendererService,
  { readonly globals: Effect.Effect<string> }
>()("@rendotdev/rig/generated/RuntimeSupportGlobalsRendererService", {
  make: Effect.gen(function* () {
    const runtimeGlobalsSource = (): string => `// Generated by Rig. Safe to overwrite.
import type { RigToolFactory as RigToolFactoryType, RigToolKit as RigToolKitType } from "./types";

declare global {
  type RigToolFactory = RigToolFactoryType;
  type RigToolKit = RigToolKitType;
}

export {};
`;
    const globals = Effect.sync(runtimeGlobalsSource).pipe(
      Effect.withSpan("RuntimeSupportGlobalsRendererService.globals"),
    );
    return { globals } as const;
  }),
}) {
  static readonly layer = Layer.effect(
    RuntimeSupportGlobalsRendererService,
    RuntimeSupportGlobalsRendererService.make,
  );
}

class RuntimeSupportRegistryTsconfigRendererService extends Context.Service<
  RuntimeSupportRegistryTsconfigRendererService,
  { readonly registryTsconfig: Effect.Effect<string> }
>()("@rendotdev/rig/generated/RuntimeSupportRegistryTsconfigRendererService", {
  make: Effect.gen(function* () {
    const paths = yield* RigPathsConfigService;
    const requireFromRuntimeSupport = createRequire(import.meta.url);
    const resolvePackage = (specifier: string): string =>
      requireFromRuntimeSupport.resolve(`${specifier}/package.json`);
    const runtimeRegistryTsconfigSource = (params: {
      dirname: typeof dirname;
      resolvePackage: (specifier: string) => string;
    }): string => `// Generated by Rig. Safe to overwrite.
${JSON.stringify(
  {
    compilerOptions: {
      target: "ES2022",
      module: "ESNext",
      moduleResolution: "Bundler",
      strict: true,
      noEmit: true,
      skipLibCheck: true,
      allowImportingTsExtensions: true,
      jsx: "preserve",
      lib: ["ES2023", "DOM"],
      types: ["bun"],
      typeRoots: [params.dirname(params.dirname(params.resolvePackage("@types/bun")))],
      paths: {
        zod: [join(params.dirname(params.resolvePackage("zod")), "index.d.ts")],
      },
    },
    files: [paths.runtimeGlobalsPath, paths.runtimeTypesPath],
    include: ["./*/index.rig.ts", "./*/index.rig.tsx"],
  },
  null,
  2,
)}
`;
    const registryTsconfig = Effect.sync(() =>
      runtimeRegistryTsconfigSource({ dirname, resolvePackage }),
    ).pipe(Effect.withSpan("RuntimeSupportRegistryTsconfigRendererService.registryTsconfig"));
    return { registryTsconfig } as const;
  }),
}) {
  static readonly layer = Layer.effect(
    RuntimeSupportRegistryTsconfigRendererService,
    RuntimeSupportRegistryTsconfigRendererService.make,
  );
}

class RuntimeSupportRendererService extends Context.Service<
  RuntimeSupportRendererService,
  {
    readonly sdk: Effect.Effect<string>;
    readonly globals: Effect.Effect<string>;
    readonly registryTsconfig: Effect.Effect<string>;
  }
>()("@rendotdev/rig/generated/RuntimeSupportRendererService", {
  make: Effect.gen(function* () {
    const sdkRenderer = yield* RuntimeSupportSdkRendererService;
    const globalsRenderer = yield* RuntimeSupportGlobalsRendererService;
    const registryRenderer = yield* RuntimeSupportRegistryTsconfigRendererService;
    const sdk = sdkRenderer.sdk.pipe(Effect.withSpan("RuntimeSupportRendererService.sdk"));
    const globals = globalsRenderer.globals.pipe(
      Effect.withSpan("RuntimeSupportRendererService.globals"),
    );
    const registryTsconfig = registryRenderer.registryTsconfig.pipe(
      Effect.withSpan("RuntimeSupportRendererService.registryTsconfig"),
    );
    return { sdk, globals, registryTsconfig } as const;
  }),
}) {
  static readonly layer = Layer.effect(
    RuntimeSupportRendererService,
    RuntimeSupportRendererService.make,
  );
}

export const runtimeSupportRendererLayer = RuntimeSupportRendererService.layer.pipe(
  Layer.provide(
    Layer.mergeAll(
      RuntimeSupportSdkRendererService.layer,
      RuntimeSupportGlobalsRendererService.layer,
      RuntimeSupportRegistryTsconfigRendererService.layer,
    ),
  ),
);

export const runtimeSupportLayer = RuntimeSupportService.layer.pipe(
  Layer.provide(
    Layer.mergeAll(
      rigPathsConfigLayer,
      atomicFileWriterLayer,
      runtimeSupportRendererLayer.pipe(Layer.provide(rigPathsConfigLayer)),
    ),
  ),
);
