import { readFile } from "node:fs/promises";
import { Context, Effect, Layer } from "effect";
import {
  AtomicFileWriterService,
  atomicFileWriterLayer,
} from "../../../providers/filesystem/atomic-file-writer";
import { rigPathsConfigLayer, rigPathsLayer } from "../../../providers/paths/rig-paths";
import { runtimeSupportRendererLayer } from "./runtime-support";
import { registryLayer } from "../../registry/service/registry";
import { ToolDiscoveryService, toolDiscoveryLayer } from "../../registry/service/tool-discovery";
import { RigError } from "../../../providers/errors/rig-error";
import { CurrentRigToolApiVersion } from "../config/tool-api";

type ToolRuntimeInstructionUpdate = {
  name: string;
  path: string;
  changed: boolean;
};

export type ToolRuntimeInstructionSyncResult = {
  tools: ToolRuntimeInstructionUpdate[];
};

const StartMarker = "// rig:runtime-reference:start";
const EndMarker = "// rig:runtime-reference:end";
const ToolApiVersionMarker = "// rig:tool-api-version";

const RuntimeReference = `Generated by Rig. This block is refreshed automatically.

Rig tool runtime:
- Tool API v2 uses a direct factory export: \`export default (rig: RigToolKit) => rig.defineTool({ ... });\`.
- Rig derives the tool name from its folder. The \`name\` property remains supported for v1 tools.
- \`rig.z\` is Zod. Docs: https://zod.dev/
- \`rig.defineTool(definition)\` defines the tool.
- Define \`commands\` as \`(command) => ({ ... })\`, then define each command with the bound \`command({ description, input, output, run })\` helper. \`rig.defineCommand\` remains supported for v1 tools.
- Use \`rig.z.object({ ... })\` for input/output schemas.
- Tools run under Bun with fallback auto-install enabled, so tool files can import npm packages; add explicit package versions when reproducibility matters. Example: \`import sharp from "sharp@0.34.4";\`.
- \`rig.run({ command: "tool.command", input })\` runs another registered Rig command and returns its data.
- \`rig.$\` runs a Bun Shell tagged template command with escaped interpolations. Docs: https://bun.com/docs/runtime/shell
- \`rig.args()\` builds argv arrays with \`.raw()\`, \`.flag()\`, \`.value()\`, \`.values()\`, and \`.toArray()\`.
- \`rig.paths.home()\`, \`rig.paths.resolve(cwd, path)\`, \`rig.paths.ensureParent(path)\`, and \`rig.paths.size(path)\` cover common path work.
- Add \`env: rig.z.object({ KEY: rig.z.string() })\` to validate local secrets or settings and receive parsed values on \`context.env\`.
- Run \`rig env <tool> KEY=VALUE\` to write the tool \`.env\` file; run \`rig env <tool> remove KEY\` to remove a value.
- To add another registry for tool files, run \`rig registry create [path]\` (defaults to current directory).

Tool logging:
- Use \`context.log.info(...)\`, \`context.log.warn(...)\`, or another Pino-style method for structured logs with a default \`tool:<tool>.<command>\` prefix.
- Rig writes app and tool logs to \`~/rig/.logs\`, rolls files by size, and keeps logs for seven days by default.

Tool key-value state:
- Use \`context.kv.set(key, value)\` and \`context.kv.get(key)\` for lightweight JSON state stored beside the tool entry file as \`kv.sqlite\`.

Tool query cache:
- Use \`await context.cache.query({ queryKey, queryFn, staleTime })\` for JSON-compatible derived data stored beside the tool entry file as \`cache.sqlite\`.
- Query keys are non-empty JSON-compatible arrays. Missing and stale data wait for \`queryFn\` and return its refreshed value; fresh data returns immediately.
- Use \`context.cache.peek(queryKey)\`, \`.set(queryKey, value)\`, \`.invalidate(queryKey)\`, \`.remove(queryKey)\`, and \`.clear()\` for explicit cache control.

Tool SQLite database:
- Add \`setupDb: (db) => { db.migrate(1, "create table", "create table ..."); }\` when a tool needs persistent state.
- Rig stores the database beside the tool entry file as \`index.sqlite\` and runs \`setupDb\` before every command.
- \`db\` is Bun SQLite with \`strict: true\`, WAL mode, and an extra \`db.migrate(version, name, sql)\` helper. Docs: https://bun.com/docs/runtime/sqlite

Tool collections:
- Add \`collections: { name: { schema: rig.z.object({ ... }) } }\` to the tool definition to declare document stores.
- Each collection is a directory of \`.md\` files (beside the tool entry file) with validated YAML frontmatter and a markdown body.
- Access via \`context.collections.<name>\` in command run functions.
- API: \`.create({ id, data, body })\`, \`.getEntry(id)\`, \`.update(id, { data, body })\`, \`.upsert({ id, data, body })\`, \`.remove(id)\`
- Query: \`.list({ where, sort, limit })\`, \`.search(query, { limit })\`, \`.count(where)\`, \`.getCollection(filterFn)\`, \`.clear()\`
- A hidden \`.index.sqlite\` with FTS5 is auto-managed for instant full-text search and structured queries on frontmatter fields.
- Files on disk are the source of truth; hand-edits are reconciled on next access.
- Optional \`generateId: (data) => string\` derives the filename from entry data; otherwise pass \`id\` explicitly.
- Schema-less collections (no \`schema\` key) are allowed; FTS still works, no validation on write.

Command run context:
- \`context.input\` is already validated by the input schema.
- \`context.env\` is already validated by the tool env schema when defined.
- \`context.processEnv\` is the process environment.
- \`context.cwd\` is the current working directory.
- \`context.db\` is available when the tool defines \`setupDb\`.
- \`context.kv\` is always available for lightweight JSON key-value state.
- \`context.cache\` is always available for persistent query data with explicit foreground refreshes.
- \`context.log\` is a structured Pino logger for this tool command.
- \`context.rig\` is the toolkit (same as the factory \`rig\` arg, useful for nested tool calls).
- \`context.collections\` provides handles for each declared collection (empty object if none defined).
- Return a value that matches the output schema.
`;

export class ToolRuntimeInstructionRendererService extends Context.Service<
  ToolRuntimeInstructionRendererService,
  {
    readonly renderPrefix: (version?: number) => Effect.Effect<string>;
    readonly upsertPrefix: (source: string) => Effect.Effect<string>;
  }
>()("@rendotdev/rig/generated/ToolRuntimeInstructionRendererService", {
  make: Effect.gen(function* () {
    const escapeRegExp = (value: string): string => value.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
    const managedBlockPattern = (): RegExp =>
      new RegExp(`${escapeRegExp(StartMarker)}[\\s\\S]*?${escapeRegExp(EndMarker)}\\n*`);
    const sourceVersion = (source: string): number => {
      const match = /^\/\/ rig:tool-api-version (\d+)\s*$/m.exec(source);
      if (!match) return 1;
      const version = Number.parseInt(match[1]!, 10);
      return Number.isSafeInteger(version) && version > 0 ? version : 1;
    };
    const renderPrefix = Effect.fn("ToolRuntimeInstructionRendererService.renderPrefix")(function* (
      version = CurrentRigToolApiVersion,
    ) {
      return [
        StartMarker,
        `${ToolApiVersionMarker} ${version}`,
        ...RuntimeReference.trimEnd()
          .split("\n")
          .map((line) => (line ? `// ${line}` : "//")),
        EndMarker,
      ].join("\n");
    });
    const upsertPrefix = Effect.fn("ToolRuntimeInstructionRendererService.upsertPrefix")(function* (
      source: string,
    ) {
      const version = sourceVersion(source);
      const withoutExisting = source
        .replace(managedBlockPattern(), "")
        .replace(/^\/\/ rig:tool-api-version \d+\s*$/gm, "")
        .trimStart();
      const shebang = withoutExisting.match(/^(#!.*\n)/);
      const prefix = yield* renderPrefix(version);
      const body = shebang ? withoutExisting.slice(shebang[0].length).trimStart() : withoutExisting;
      const next = [prefix, body.trimEnd()].filter(Boolean).join("\n\n");
      return `${shebang?.[0] ?? ""}${next}\n`;
    });
    return { renderPrefix, upsertPrefix } as const;
  }),
}) {
  // oxfmt-ignore
  static readonly layer = Layer.effect(ToolRuntimeInstructionRendererService, ToolRuntimeInstructionRendererService.make);
}

export class ToolRuntimeInstructionSyncService extends Context.Service<
  ToolRuntimeInstructionSyncService,
  { readonly sync: Effect.Effect<ToolRuntimeInstructionSyncResult, RigError> }
>()("@rendotdev/rig/generated/ToolRuntimeInstructionSyncService", {
  make: Effect.gen(function* () {
    const discovery = yield* ToolDiscoveryService;
    const renderer = yield* ToolRuntimeInstructionRendererService;
    const writer = yield* AtomicFileWriterService;
    const toError = (cause: unknown): RigError =>
      cause instanceof RigError
        ? cause
        : new RigError({
            code: "INTERNAL_ERROR",
            message: cause instanceof Error ? cause.message : String(cause),
          });
    const updateFile = Effect.fn("ToolRuntimeInstructionSyncService.updateFile")(function* (
      path: string,
    ) {
      const existing = yield* Effect.tryPromise({
        try: () =>
          typeof Bun !== "undefined" && typeof Bun.file === "function"
            ? Bun.file(path).text()
            : readFile(path, "utf8"),
        catch: toError,
      });
      const next = yield* renderer.upsertPrefix(existing);
      if (next === existing) return false;
      yield* writer.write(path, next).pipe(Effect.mapError((error) => toError(error.cause)));
      return true;
    });
    const sync = Effect.gen(function* () {
      const tools = yield* discovery.discover();
      const updates = yield* Effect.all(
        tools.map((tool) =>
          updateFile(tool.toolPath).pipe(
            Effect.map((changed) => ({ name: tool.name, path: tool.toolPath, changed })),
          ),
        ),
        { concurrency: "unbounded" },
      );
      return { tools: updates };
    }).pipe(Effect.withSpan("ToolRuntimeInstructionSyncService.sync"));
    return { sync } as const;
  }),
}) {
  // oxfmt-ignore
  static readonly layer = Layer.effect(ToolRuntimeInstructionSyncService, ToolRuntimeInstructionSyncService.make);
}

const runtimeRendererForToolSyncLayer = runtimeSupportRendererLayer.pipe(
  Layer.provide(rigPathsConfigLayer),
);
const registryForToolSyncLayer = registryLayer.pipe(
  Layer.provide(Layer.merge(atomicFileWriterLayer, runtimeRendererForToolSyncLayer)),
);
const discoveryForToolSyncLayer = toolDiscoveryLayer.pipe(
  Layer.provide(Layer.merge(registryForToolSyncLayer, rigPathsLayer)),
);
export const toolRuntimeInstructionSyncLayer = ToolRuntimeInstructionSyncService.layer.pipe(
  Layer.provide(
    Layer.mergeAll(
      ToolRuntimeInstructionRendererService.layer,
      discoveryForToolSyncLayer,
      atomicFileWriterLayer,
    ),
  ),
);
