import { defineConfig } from "vite-plus";

export default defineConfig({
  run: {
    cache: {
      scripts: false,
      tasks: true,
    },
    tasks: {
      typecheck: {
        command: "tsc --noEmit",
        input: [
          "src/**",
          "scripts/**",
          "test/**",
          "package.json",
          "tsconfig.json",
          "vite.config.ts",
        ],
        output: [],
      },
      "effect:diagnostics": {
        command: "bun run src/tooling/effect/effect-diagnostics.ts",
        input: ["src/**", "scripts/**", "test/**", "package.json", "tsconfig.json", "bun.lock"],
        output: [],
      },
      "effect:reference": {
        command: "git submodule update --init --depth 1 --recommend-shallow repos/effect",
        cache: false,
      },
      check: {
        command: "vp check",
        dependsOn: ["typecheck", "effect:diagnostics"],
        input: [
          "src/**",
          "scripts/**",
          "test/**",
          "package.json",
          "tsconfig.json",
          "vite.config.ts",
        ],
        output: [],
      },
      "dead-code": {
        command: "knip-bun --treat-config-hints-as-errors",
        input: [
          "src/**",
          "scripts/**",
          "test/**",
          "knip.ts",
          "package.json",
          "tsconfig.json",
          "vite.config.ts",
        ],
        output: [],
      },
      build: {
        command: "vp pack",
        input: ["src/**", "package.json", "tsconfig.json", "vite.config.ts", "bun.lock"],
        output: ["dist/**"],
      },
      "build:package": {
        command: 'bun -e "void 0"',
        dependsOn: ["build"],
        cache: false,
      },
      test: {
        command: "vp test run src scripts test/domains --coverage",
        dependsOn: ["check"],
        input: [
          "src/**",
          "scripts/**",
          "test/domains/**",
          "package.json",
          "tsconfig.json",
          "vite.config.ts",
        ],
        output: ["coverage/**"],
      },
      "test:e2e": {
        command: "vp test run test/e2e --coverage.enabled=false",
        dependsOn: ["build", "test"],
        input: ["test/e2e/**", "package.json", "tsconfig.json", "vite.config.ts"],
        output: [],
      },
      smoke: {
        command: "bun run scripts/smoke.ts",
        dependsOn: ["build", "test:e2e"],
        input: ["dist/**", "scripts/smoke.ts", "scripts/lib/smoke.ts"],
        output: [],
      },
      "package:check": {
        command: "npm pack --dry-run --ignore-scripts",
        dependsOn: ["build"],
        input: ["dist/**", "package.json", "README.md", "LICENSE"],
        output: [],
      },
      validate: {
        command: "bun -e \"console.log('Validation complete.')\"",
        dependsOn: ["test", "test:e2e", "smoke"],
        output: [],
      },
      ci: {
        command: "bun -e \"console.log('CI validation complete.')\"",
        dependsOn: ["validate", "package:check", "dead-code"],
        output: [],
      },
      bench: {
        command: "bun run scripts/bench.ts",
        dependsOn: ["build"],
        cache: false,
      },
      release: {
        command: "bun run scripts/release.ts",
        cache: false,
      },
      "release:beta": {
        command: "bun run scripts/release.ts beta",
        cache: false,
      },
      "release:dry-run": {
        command: "bun run scripts/release.ts --dry-run",
        cache: false,
      },
      "release:major": {
        command: "bun run scripts/release.ts major",
        cache: false,
      },
      "release:minor": {
        command: "bun run scripts/release.ts minor",
        cache: false,
      },
      "release:patch": {
        command: "bun run scripts/release.ts patch",
        cache: false,
      },
      dev: {
        command: "vp pack --watch",
        cache: false,
      },
      format: {
        command: "vp fmt",
        cache: false,
      },
      lint: {
        command: "vp lint --deny-warnings",
        input: [
          "src/**",
          "scripts/**",
          "test/**",
          "package.json",
          "tsconfig.json",
          "vite.config.ts",
        ],
        output: [],
      },
      "test:watch": {
        command: "vp test watch",
        cache: false,
      },
    },
  },
  pack: {
    deps: {
      alwaysBundle: [/^effect\//],
      neverBundle: ["ink", "react", "typescript", /^bun:/],
      onlyBundle: false,
    },
    entry: {
      bin: "src/app/cli/entrypoint.ts",
      rig: "src/app/cli/module-entrypoint.ts",
    },
    format: "esm",
    outDir: "dist",
    platform: "node",
    target: "node20",
  },
  ssr: {
    external: ["typescript", "bun:sqlite"],
  },
  test: {
    environment: "node",
    globals: false,
    include: [
      "src/**/*.test.{ts,tsx}",
      "scripts/**/*.test.ts",
      "test/domains/**/*.test.ts",
      "test/e2e/**/*.e2e.test.ts",
    ],
    passWithNoTests: false,
    restoreMocks: true,
    testTimeout: 30_000,
    coverage: {
      provider: "v8",
      include: ["src/**/*.{ts,tsx}"],
      exclude: [
        "src/**/*.d.ts",
        "src/**/*.test.{ts,tsx}",
        "src/tooling/**",
        "src/domains/tools/service/help-topics.ts",
      ],
      reporter: ["text", "json-summary"],
      thresholds: {
        branches: -512,
        functions: -286,
        lines: -478,
        statements: -565,
      },
    },
  },
  fmt: {
    printWidth: 100,
    tabWidth: 2,
    useTabs: false,
    semi: true,
    singleQuote: false,
    trailingComma: "all",
    insertFinalNewline: true,
    sortPackageJson: true,
    ignorePatterns: ["AGENTS.md", "dist/**", "coverage/**", "node_modules/**", "repos/**"],
  },
  lint: {
    env: {
      builtin: true,
      node: true,
      vitest: true,
    },
    plugins: ["typescript", "unicorn", "promise", "node", "vitest"],
    categories: {
      correctness: "error",
      suspicious: "warn",
      perf: "warn",
    },
    rules: {
      "rig/domain-public-api": "error",
      "rig/effect-runtime-boundary": "error",
      "rig/effect-service-contract": "error",
      "rig/layer-boundaries": "error",
      "rig/max-file-lines": "error",
      "rig/max-function-lines": "error",
      "rig/named-compound-if-condition": "error",
      "rig/no-barrel-files": "error",
      "rig/no-floating-behavior": "error",
      "rig/source-location": "error",
      "typescript/no-base-to-string": "off",
      "typescript/no-extraneous-class": "off",
      "typescript/no-redundant-type-constituents": "off",
      "typescript/no-unnecessary-type-arguments": "off",
      "typescript/no-unnecessary-type-assertion": "off",
      "typescript/no-unnecessary-type-conversion": "off",
      "typescript/no-unnecessary-type-parameters": "off",
      "typescript/no-unsafe-type-assertion": "off",
      "typescript/restrict-template-expressions": "off",
      "typescript/unbound-method": "off",
      "no-useless-call": "off",
      "require-yield": "off",
      "unicorn/consistent-function-scoping": "off",
      "vitest/require-mock-type-parameters": "off",
      "vite-plus/prefer-vite-plus-imports": "error",
    },
    ignorePatterns: ["dist/**", "coverage/**", "node_modules/**", "repos/**"],
    options: {
      typeAware: true,
      typeCheck: true,
    },
    jsPlugins: [
      {
        name: "rig",
        specifier: "./src/tooling/oxlint/oxlint-plugin.ts",
      },
      {
        name: "vite-plus",
        specifier: "vite-plus/oxlint-plugin",
      },
    ],
  },
});
