import { mkdir, writeFile } from "node:fs/promises";
import { RigPaths, type PathOptions } from "../config/paths";

export class RuntimeSupport {
  private readonly paths: RigPaths;

  constructor(options: PathOptions = {}) {
    this.paths = new RigPaths(options);
  }

  async ensure(): Promise<void> {
    await mkdir(this.paths.runtimeDir, { recursive: true });
    const zodImport = this.resolveImport("zod");
    const content = `// Generated by Rig. Safe to overwrite.\nimport * as zodModule from ${JSON.stringify(zodImport)};\n\nexport const z = (zodModule as any).z ?? zodModule;\n\nexport class RigTool {\n  static define(definition: any): any {\n    return definition;\n  }\n}\n`;
    await writeFile(this.paths.runtimeSdkPath, content, "utf8");
  }

  private resolveImport(specifier: string): string {
    const meta = import.meta as ImportMeta & { resolve?: (id: string) => string };
    if (!meta.resolve) return specifier;
    return meta.resolve(specifier);
  }
}
