import { existsSync } from "node:fs";
import { mkdir, readFile, writeFile } from "node:fs/promises";
import { join } from "node:path";
import { RigPaths, type PathOptions } from "../config/paths";
import { RigPackageRoot } from "./package-root";

export class RuntimeSupport {
  private readonly paths: RigPaths;

  constructor(options: PathOptions = {}) {
    this.paths = new RigPaths(options);
  }

  async ensure(registryDirs: string[] = []): Promise<void> {
    await mkdir(this.paths.runtimeDir, { recursive: true });
    const zodImport = this.resolveImport("zod");
    await writeFile(this.paths.runtimeSdkPath, this.sdkSource(zodImport), "utf8");
    await writeFile(this.paths.runtimeTypesPath, this.typesSource(), "utf8");
    await writeFile(this.paths.runtimeGlobalsPath, this.globalsSource(), "utf8");
    await Promise.all(registryDirs.map((dir) => this.ensureRegistryTsconfig(dir)));
  }

  private async ensureRegistryTsconfig(registryDir: string): Promise<void> {
    await mkdir(registryDir, { recursive: true });
    const tsconfigPath = join(registryDir, "tsconfig.json");
    const content = this.registryTsconfigSource();
    if (existsSync(tsconfigPath)) {
      const existing = await readFile(tsconfigPath, "utf8");
      if (!existing.startsWith("// Generated by Rig.")) return;
    }
    await writeFile(tsconfigPath, content, "utf8");
  }

  private sdkSource(zodImport: string): string {
    return `// Generated by Rig. Safe to overwrite.
import { spawn } from "node:child_process";
import { existsSync, statSync } from "node:fs";
import { mkdir } from "node:fs/promises";
import { homedir } from "node:os";
import { dirname, isAbsolute, join, resolve } from "node:path";
import * as zodModule from ${JSON.stringify(zodImport)};

export const z = (zodModule as any).z ?? zodModule;
export const rigSchemaRoleSymbol = Symbol.for("rig.schemaRole");

class RigPathRuntime {
  home() { return homedir(); }
  resolve(cwd, pathValue) {
    if (pathValue === "~") return homedir();
    if (pathValue.startsWith("~/")) return join(homedir(), pathValue.slice(2));
    return isAbsolute(pathValue) ? pathValue : resolve(cwd, pathValue);
  }
  async ensureParent(pathValue) { await mkdir(dirname(pathValue), { recursive: true }); }
  size(pathValue) { return existsSync(pathValue) ? statSync(pathValue).size : 0; }
}

class RigArgsRuntime {
  args = [];
  raw(...values) { this.args.push(...values); return this; }
  flag(name, enabled = true) { if (enabled) this.args.push(name); return this; }
  value(name, value) { if (value !== undefined && value !== null) this.args.push(name, String(value)); return this; }
  values(name, values) { for (const value of values ?? []) this.args.push(name, value); return this; }
  toArray() { return [...this.args]; }
}

class RigShellRuntime {
  async $(strings, ...values) { return this.bash(this.renderTemplateCommand(strings, values)); }
  async bash(command, options = {}) { return this.exec(["bash", "-lc", command], options); }
  async exec(args, options = {}) {
    const proc = spawn(args[0], args.slice(1), {
      cwd: options.cwd ?? process.cwd(),
      env: { ...process.env, ...options.env },
      stdio: ["ignore", "pipe", "pipe"],
    });
    const [stdout, stderr, exitCode] = await Promise.all([
      this.readStream(proc.stdout),
      this.readStream(proc.stderr),
      new Promise((resolve) => proc.on("close", (code) => resolve(code ?? 1))),
    ]);
    return { command: args, stdout, stderr, exitCode };
  }
  async json(args, options = {}) {
    const result = await this.exec(args, options);
    if (result.exitCode !== 0) throw new Error("Command failed before JSON could be parsed.");
    return JSON.parse(result.stdout);
  }
  renderTemplateCommand(strings, values) {
    return strings.reduce((command, part, index) => command + part + (index < values.length ? this.renderTemplateValue(values[index]) : ""), "");
  }
  renderTemplateValue(value) {
    if (Array.isArray(value)) return value.map((item) => this.shellQuote(String(item))).join(" ");
    return this.shellQuote(String(value));
  }
  shellQuote(value) {
    if (/^[A-Za-z0-9_./:=@%+,-]+$/.test(value)) return value;
    return "'" + value.replaceAll("'", "'\\''") + "'";
  }
  async readStream(stream) {
    const chunks = [];
    for await (const chunk of stream) chunks.push(Buffer.isBuffer(chunk) ? chunk : Buffer.from(String(chunk)));
    return Buffer.concat(chunks).toString("utf8");
  }
}

function isZodSchema(value) {
  return typeof value === "object" && value !== null && typeof value.safeParse === "function";
}

function schema(value, role) {
  const result = isZodSchema(value) ? value : z.object(value);
  if (result[rigSchemaRoleSymbol] === role) return result;
  Object.defineProperty(result, rigSchemaRoleSymbol, {
    value: role,
    configurable: false,
    enumerable: false,
    writable: false,
  });
  return result;
}

export const rig = {
  z,
  defineTool: (definition) => definition,
  command: (definition) => definition,
  input: (value) => schema(value, "input"),
  output: (value) => schema(value, "output"),
  args: () => new RigArgsRuntime(),
  paths: new RigPathRuntime(),
  shell: new RigShellRuntime(),
};

export function defineTool(value) {
  return typeof value === "function" ? value : rig.defineTool(value);
}

export const command = rig.command;
export const input = rig.input;
export const output = rig.output;
export const args = rig.args;
export const paths = rig.paths;

export class RigTool {
  static define(value) {
    return defineTool(value);
  }
}
`;
  }

  private typesSource(): string {
    return `// Generated by Rig. Safe to overwrite.
import type { z } from "zod";

declare const RigInputSchemaBrand: unique symbol;
declare const RigOutputSchemaBrand: unique symbol;

export type RigInputSchema<T extends z.ZodTypeAny = z.ZodTypeAny> = T & {
  readonly [RigInputSchemaBrand]: T;
};

export type RigOutputSchema<T extends z.ZodTypeAny = z.ZodTypeAny> = T & {
  readonly [RigOutputSchemaBrand]: T;
};

export type RigSchemaFromValue<T extends z.ZodTypeAny | z.ZodRawShape> = T extends z.ZodTypeAny
  ? T
  : T extends z.ZodRawShape
    ? z.ZodObject<T>
    : never;

export type RigShellOptions = {
  cwd?: string;
  env?: Record<string, string | undefined>;
  timeoutMs?: number;
  maxOutputBytes?: number;
};

export type RigShellResult = {
  command: string[];
  stdout: string;
  stderr: string;
  exitCode: number;
};

export type RigShell = {
  $(strings: TemplateStringsArray, ...values: unknown[]): Promise<RigShellResult>;
  exec(args: string[], options?: RigShellOptions): Promise<RigShellResult>;
  bash(command: string, options?: RigShellOptions): Promise<RigShellResult>;
  json(args: string[], options?: RigShellOptions): Promise<unknown>;
};

export type RigPathHelper = {
  home(): string;
  resolve(cwd: string, pathValue: string): string;
  ensureParent(pathValue: string): Promise<void>;
  size(pathValue: string): number;
};

export type RigArgBuilder = {
  raw(...values: string[]): RigArgBuilder;
  flag(name: string, enabled?: boolean): RigArgBuilder;
  value(name: string, value: string | number | boolean | undefined | null): RigArgBuilder;
  values(name: string, values: string[] | undefined): RigArgBuilder;
  toArray(): string[];
};

export type RigToolRunContext<Input> = {
  input: Input;
  env: NodeJS.ProcessEnv;
  cwd: string;
  shell: RigShell;
  rig: RigToolKit;
};

export type RigToolExample<Input = any, Output = any> = {
  title: string;
  text: string;
  input?: Input;
  output?: Output;
};

export type RigCommandDefinition<
  Input extends RigInputSchema = RigInputSchema,
  Output extends RigOutputSchema = RigOutputSchema,
> = {
  description: string;
  input: Input;
  output: Output;
  examples?: RigToolExample<z.input<Input>, z.output<Output>>[];
  run: (ctx: RigToolRunContext<z.output<Input>>) => z.input<Output> | Promise<z.input<Output>>;
};

export type RigToolDefinition = {
  name: string;
  description: string;
  commands: Record<string, RigCommandDefinition>;
};

export type RigToolKit = {
  z: typeof z;
  defineTool<T extends RigToolDefinition>(definition: T): T;
  command<I extends RigInputSchema, O extends RigOutputSchema>(definition: RigCommandDefinition<I, O>): RigCommandDefinition<I, O>;
  input<T extends z.ZodTypeAny | z.ZodRawShape>(value: T): RigInputSchema<RigSchemaFromValue<T>>;
  output<T extends z.ZodTypeAny | z.ZodRawShape>(value: T): RigOutputSchema<RigSchemaFromValue<T>>;
  args(): RigArgBuilder;
  paths: RigPathHelper;
  shell: RigShell;
};

export type RigToolFactory = (rig: RigToolKit) => RigToolDefinition | Promise<RigToolDefinition>;
`;
  }

  private globalsSource(): string {
    return `// Generated by Rig. Safe to overwrite.
import type { RigToolFactory as RigToolFactoryType, RigToolKit as RigToolKitType } from "./types";

declare global {
  type RigToolFactory = RigToolFactoryType;
  type RigToolKit = RigToolKitType;
}

export {};
`;
  }

  private registryTsconfigSource(): string {
    return `// Generated by Rig. Safe to overwrite.
${JSON.stringify(
  {
    compilerOptions: {
      target: "ES2022",
      module: "ESNext",
      moduleResolution: "Bundler",
      strict: true,
      noEmit: true,
      ignoreDeprecations: "6.0",
      skipLibCheck: true,
      allowImportingTsExtensions: true,
      jsx: "preserve",
      lib: ["ES2023", "DOM"],
      types: ["bun"],
      typeRoots: [join(this.repoRoot(), "node_modules/@types")],
      baseUrl: this.repoRoot(),
      paths: {
        zod: [join(this.repoRoot(), "node_modules/zod/index.d.ts")],
      },
    },
    files: [this.paths.runtimeGlobalsPath, this.paths.runtimeTypesPath],
    include: ["./*/index.rig.ts", "./*/index.rig.tsx"],
  },
  null,
  2,
)}
`;
  }

  private repoRoot(): string {
    return RigPackageRoot.find(import.meta.url);
  }

  private resolveImport(specifier: string): string {
    const meta = import.meta as ImportMeta & { resolve?: (id: string) => string };
    /* v8 ignore next */
    if (!meta.resolve) return specifier;
    return meta.resolve(specifier);
  }
}
