import { existsSync } from "node:fs";
import { mkdir, readFile, writeFile } from "node:fs/promises";
import { join } from "node:path";
import { RigPaths, type PathOptions } from "../config/paths";
import { RigPackageRoot } from "./package-root";

type BunFileApi = {
  file(path: string): {
    exists(): Promise<boolean>;
    text(): Promise<string>;
  };
  write(path: string, content: string): Promise<number>;
};

export class RuntimeSupport {
  private readonly paths: RigPaths;

  constructor(options: PathOptions = {}) {
    this.paths = new RigPaths(options);
  }

  async ensure(registryDirs: string[] = []): Promise<void> {
    await mkdir(this.paths.runtimeDir, { recursive: true });
    const zodImport = this.resolveImport("zod");
    await Promise.all([
      this.writeTextIfChanged(this.paths.runtimeSdkPath, this.sdkSource(zodImport)),
      this.writeTextIfChanged(this.paths.runtimeTypesPath, this.typesSource()),
      this.writeTextIfChanged(this.paths.runtimeGlobalsPath, this.globalsSource()),
    ]);
    await Promise.all(registryDirs.map((dir) => this.ensureRegistryTsconfig(dir)));
  }

  private async ensureRegistryTsconfig(registryDir: string): Promise<void> {
    await mkdir(registryDir, { recursive: true });
    const tsconfigPath = join(registryDir, "tsconfig.json");
    const content = this.registryTsconfigSource();
    const existing = await this.readTextIfExists(tsconfigPath);
    if (existing !== undefined && !existing.startsWith("// Generated by Rig.")) return;
    await this.writeTextIfChanged(tsconfigPath, content);
  }

  private async writeTextIfChanged(path: string, content: string): Promise<void> {
    if ((await this.readTextIfExists(path)) === content) return;

    const bun = this.bunFileApi();
    /* v8 ignore next 4 */
    if (bun) {
      await bun.write(path, content);
      return;
    }

    await writeFile(path, content, "utf8");
  }

  private async readTextIfExists(path: string): Promise<string | undefined> {
    const bun = this.bunFileApi();
    /* v8 ignore next 5 */
    if (bun) {
      const file = bun.file(path);
      if (!(await file.exists())) return undefined;
      return file.text();
    }

    if (!existsSync(path)) return undefined;
    return readFile(path, "utf8");
  }

  private bunFileApi(): BunFileApi | undefined {
    const candidate = (globalThis as typeof globalThis & { Bun?: Partial<BunFileApi> }).Bun;
    /* v8 ignore next 3 */
    if (typeof candidate?.file === "function" && typeof candidate.write === "function") {
      return candidate as BunFileApi;
    }
    return undefined;
  }

  private sdkSource(zodImport: string): string {
    return `// Generated by Rig. Safe to overwrite.
// @ts-nocheck
import { spawn } from "node:child_process";
import { existsSync, statSync } from "node:fs";
import { mkdir } from "node:fs/promises";
import { homedir } from "node:os";
import { dirname, isAbsolute, join, resolve } from "node:path";
import type { z as zodNamespace } from "zod";
import type { RigToolDefinition, RigToolFactory, RigToolKit } from "./types";
// @ts-ignore file URL imports are emitted so generated tools can load Rig's bundled Zod.
import * as zodModule from ${JSON.stringify(zodImport)};

export const z: typeof zodNamespace = (zodModule as any).z ?? zodModule;

class RigPathRuntime {
  home() { return homedir(); }
  resolve(cwd, pathValue) {
    if (pathValue === "~") return homedir();
    if (pathValue.startsWith("~/")) return join(homedir(), pathValue.slice(2));
    return isAbsolute(pathValue) ? pathValue : resolve(cwd, pathValue);
  }
  async ensureParent(pathValue) { await mkdir(dirname(pathValue), { recursive: true }); }
  size(pathValue) { return existsSync(pathValue) ? statSync(pathValue).size : 0; }
}

class RigArgsRuntime {
  args = [];
  raw(...values) { this.args.push(...values); return this; }
  flag(name, enabled = true) { if (enabled) this.args.push(name); return this; }
  value(name, value) { if (value !== undefined && value !== null) this.args.push(name, String(value)); return this; }
  values(name, values) { for (const value of values ?? []) this.args.push(name, value); return this; }
  toArray() { return [...this.args]; }
}

class RigShellRuntime {
  async $(strings, ...values) {
    const bun = this.bun();
    if (bun) return this.runBunShell(bun.$(strings, ...values), [this.renderTemplateCommand(strings, values)]);
    return this.bash(this.renderTemplateCommand(strings, values));
  }
  async bash(command, options = {}) {
    const bun = this.bun();
    if (bun) return this.runBunShell(bun.$(this.rawTemplate(command)), [command], options);
    return this.exec(["bash", "-lc", command], options);
  }
  async exec(args, options = {}) {
    const bun = this.bun();
    if (bun) return this.runBunShell(bun.$(this.interpolationTemplate(), args), args, options);
    const proc = spawn(args[0], args.slice(1), {
      cwd: options.cwd ?? process.cwd(),
      env: { ...process.env, ...options.env },
      stdio: ["ignore", "pipe", "pipe"],
    });
    const [stdout, stderr, exitCode] = await Promise.all([
      this.readStream(proc.stdout),
      this.readStream(proc.stderr),
      new Promise((resolve) => proc.on("close", (code) => resolve(code ?? 1))),
    ]);
    return { command: args, stdout, stderr, exitCode };
  }
  async json(args, options = {}) {
    const result = await this.exec(args, options);
    if (result.exitCode !== 0) throw new Error("Command failed before JSON could be parsed.");
    return JSON.parse(result.stdout);
  }
  async runBunShell(shell, command, options = {}) {
    let configured = shell.nothrow();
    if (options.cwd) configured = configured.cwd(options.cwd);
    if (options.env) configured = configured.env({ ...process.env, ...options.env });
    const output = await configured.quiet();
    return {
      command,
      stdout: output.stdout.toString("utf8"),
      stderr: output.stderr.toString("utf8"),
      exitCode: output.exitCode,
    };
  }
  rawTemplate(command) { return Object.assign([command], { raw: [command] }); }
  interpolationTemplate() { return Object.assign(["", ""], { raw: ["", ""] }); }
  bun() { return typeof globalThis.Bun?.$ === "function" ? globalThis.Bun : undefined; }
  renderTemplateCommand(strings, values) {
    return strings.reduce((command, part, index) => command + part + (index < values.length ? this.renderTemplateValue(values[index]) : ""), "");
  }
  renderTemplateValue(value) {
    if (Array.isArray(value)) return value.map((item) => this.shellQuote(String(item))).join(" ");
    return this.shellQuote(String(value));
  }
  shellQuote(value) {
    if (/^[A-Za-z0-9_./:=@%+,-]+$/.test(value)) return value;
    return "'" + value.replaceAll("'", "'\\''") + "'";
  }
  async readStream(stream) {
    const chunks = [];
    for await (const chunk of stream) chunks.push(Buffer.isBuffer(chunk) ? chunk : Buffer.from(String(chunk)));
    return Buffer.concat(chunks).toString("utf8");
  }
}

class RigCommandRunnerRuntime {
  async run(options) {
    const id = options.tool ? options.tool + "." + options.command : options.command;
    if (!id || id.split(".").length !== 2) throw new Error("Command id must use <tool>.<command>: " + id);
    if (options.input !== undefined && options.args?.length) throw new Error("Use input or args, not both.");

    const args = ["rig", "run", id];
    if (options.input !== undefined) args.push("--input", JSON.stringify(options.input));
    if (options.dryRun) args.push("--dry-run");
    args.push(...(options.args ?? []));

    const result = await new RigShellRuntime().exec(args);
    if (result.exitCode !== 0) throw new Error("Rig tool command failed: " + id + "\\n" + result.stderr);

    const envelope = JSON.parse(result.stdout);
    if (envelope.errors?.length) throw new Error("Rig tool command failed: " + id + "\\n" + JSON.stringify(envelope.errors, null, 2));
    return envelope.data;
  }
}

const rigShell = new RigShellRuntime();

export const rig: RigToolKit = {
  z,
  defineTool: (definition) => definition,
  defineCommand: (definition) => definition,
  run: (options) => new RigCommandRunnerRuntime().run(options),
  $: (strings, ...values) => rigShell.$(strings, ...values),
  args: () => new RigArgsRuntime(),
  paths: new RigPathRuntime(),
  shell: rigShell,
} as unknown as RigToolKit;

function defineToolRuntime<T extends RigToolDefinition | RigToolFactory>(value: T): T {
  return typeof value === "function" ? value : rig.defineTool(value as RigToolDefinition) as T;
}

export class RigTool {
  static define<T extends RigToolDefinition | RigToolFactory>(value: T): T {
    return defineToolRuntime(value);
  }
}
`;
  }

  private typesSource(): string {
    return `// Generated by Rig. Safe to overwrite.
import type { Database } from "bun:sqlite";
import type { z } from "zod";

export type RigSchema = z.ZodTypeAny;

export type RigShellOptions = {
  cwd?: string;
  env?: Record<string, string | undefined>;
  timeoutMs?: number;
  maxOutputBytes?: number;
};

export type RigShellResult = {
  command: string[];
  stdout: string;
  stderr: string;
  exitCode: number;
};

export type RigShell = {
  $(strings: TemplateStringsArray, ...values: unknown[]): Promise<RigShellResult>;
  exec(args: string[], options?: RigShellOptions): Promise<RigShellResult>;
  bash(command: string, options?: RigShellOptions): Promise<RigShellResult>;
  json(args: string[], options?: RigShellOptions): Promise<unknown>;
};

export type RigPathHelper = {
  home(): string;
  resolve(cwd: string, pathValue: string): string;
  ensureParent(pathValue: string): Promise<void>;
  size(pathValue: string): number;
};

export type RigArgBuilder = {
  raw(...values: string[]): RigArgBuilder;
  flag(name: string, enabled?: boolean): RigArgBuilder;
  value(name: string, value: string | number | boolean | undefined | null): RigArgBuilder;
  values(name: string, values: string[] | undefined): RigArgBuilder;
  toArray(): string[];
};

export type RigRunOptions = {
  tool?: string;
  command: string;
  input?: unknown;
  args?: string[];
  dryRun?: boolean;
};

export type RigToolDatabase = Database & {
  readonly path: string;
  migrate(version: number, name: string, sql: string): void;
};

export type RigToolKvStore = {
  readonly path: string;
  get<T = unknown>(key: string): T | undefined;
  set(key: string, value: unknown): void;
};

export type RigLogMethod = {
  (message: string): void;
  (bindings: Record<string, unknown>, message?: string): void;
  (error: Error, message?: string): void;
};

export type RigToolLogger = {
  trace: RigLogMethod;
  debug: RigLogMethod;
  info: RigLogMethod;
  warn: RigLogMethod;
  error: RigLogMethod;
  fatal: RigLogMethod;
  child(bindings: Record<string, unknown>): RigToolLogger;
};

export type RigToolRunContext<Input, Env = unknown> = {
  input: Input;
  env: Env;
  processEnv: NodeJS.ProcessEnv;
  cwd: string;
  db: RigToolDatabase;
  kv: RigToolKvStore;
  log: RigToolLogger;
  rig: RigToolKit;
};

export type RigToolExample<Input = any, Output = any> = {
  title: string;
  text: string;
  input?: Input;
  output?: Output;
};

export type RigCommandDefinition<
  Input extends RigSchema = RigSchema,
  Output extends RigSchema = RigSchema,
  Env = unknown,
> = {
  description: string;
  input: Input;
  output: Output;
  examples?: RigToolExample<z.input<Input>, z.output<Output>>[];
  run: (ctx: RigToolRunContext<z.output<Input>, Env>) => z.input<Output> | Promise<z.input<Output>>;
};

export type RigToolDefinition<Env extends RigSchema = RigSchema> = {
  name: string;
  description: string;
  env?: Env;
  setupDb?: (db: RigToolDatabase) => void | Promise<void>;
  commands: Record<string, RigCommandDefinition<RigSchema, RigSchema, z.output<Env>>>;
};

export type RigToolKit = {
  z: typeof z;
  defineTool<T extends RigToolDefinition>(definition: T): T;
  defineCommand<I extends RigSchema, O extends RigSchema>(definition: RigCommandDefinition<I, O>): RigCommandDefinition<I, O>;
  run<T = unknown>(options: RigRunOptions): Promise<T>;
  $(strings: TemplateStringsArray, ...values: unknown[]): Promise<RigShellResult>;
  args(): RigArgBuilder;
  paths: RigPathHelper;
  shell: RigShell;
};

export type RigToolFactory = (rig: RigToolKit) => RigToolDefinition | Promise<RigToolDefinition>;
`;
  }

  private globalsSource(): string {
    return `// Generated by Rig. Safe to overwrite.
import type { RigToolFactory as RigToolFactoryType, RigToolKit as RigToolKitType } from "./types";

declare global {
  type RigToolFactory = RigToolFactoryType;
  type RigToolKit = RigToolKitType;
}

export {};
`;
  }

  private registryTsconfigSource(): string {
    return `// Generated by Rig. Safe to overwrite.
${JSON.stringify(
  {
    compilerOptions: {
      target: "ES2022",
      module: "ESNext",
      moduleResolution: "Bundler",
      strict: true,
      noEmit: true,
      ignoreDeprecations: "6.0",
      skipLibCheck: true,
      allowImportingTsExtensions: true,
      jsx: "preserve",
      lib: ["ES2023", "DOM"],
      types: ["bun"],
      typeRoots: [join(this.repoRoot(), "node_modules/@types")],
      baseUrl: this.repoRoot(),
      paths: {
        zod: [join(this.repoRoot(), "node_modules/zod/index.d.ts")],
      },
    },
    files: [this.paths.runtimeGlobalsPath, this.paths.runtimeTypesPath],
    include: ["./*/index.rig.ts", "./*/index.rig.tsx"],
  },
  null,
  2,
)}
`;
  }

  private repoRoot(): string {
    return RigPackageRoot.find(import.meta.url);
  }

  private resolveImport(specifier: string): string {
    const meta = import.meta as ImportMeta & { resolve?: (id: string) => string };
    /* v8 ignore next */
    if (!meta.resolve) return specifier;
    return meta.resolve(specifier);
  }
}
