export const ErrorCodes = {
  CONFIG_INVALID: "CONFIG_INVALID",
  DUPLICATE_TOOL: "DUPLICATE_TOOL",
  TOOL_NOT_FOUND: "TOOL_NOT_FOUND",
  COMMAND_NOT_FOUND: "COMMAND_NOT_FOUND",
  TOOL_INVALID: "TOOL_INVALID",
  VALIDATION_ERROR: "VALIDATION_ERROR",
  OUTPUT_VALIDATION_ERROR: "OUTPUT_VALIDATION_ERROR",
  POLICY_CONFIRMATION_REQUIRED: "POLICY_CONFIRMATION_REQUIRED",
  INPUT_ERROR: "INPUT_ERROR",
  SHELL_ERROR: "SHELL_ERROR",
  TYPECHECK_ERROR: "TYPECHECK_ERROR",
  DEV_LINK_ERROR: "DEV_LINK_ERROR",
} as const;

export type ErrorCode = (typeof ErrorCodes)[keyof typeof ErrorCodes];
