export const RuntimeSupportSdkSourceTemplate = `// Generated by Rig. Safe to overwrite.
// @ts-nocheck
import { spawn } from "node:child_process";
import { existsSync, statSync } from "node:fs";
import { mkdir } from "node:fs/promises";
import { homedir } from "node:os";
import { dirname, isAbsolute, join, resolve } from "node:path";
import type { z as zodNamespace } from "zod";
import type { RigToolDefinition, RigToolFactory, RigToolKit } from "./types";
// @ts-ignore file URL imports are emitted so generated tools can load Rig's bundled Zod.
import * as zodModule from __RIG_ZOD_IMPORT__;

export const z: typeof zodNamespace = (zodModule as any).z ?? zodModule;

function makeRigPathRuntime() {
  return {
    home: () => homedir(),
    resolve(cwd, pathValue) {
      if (pathValue === "~") return homedir();
      if (pathValue.startsWith("~/")) return join(homedir(), pathValue.slice(2));
      return isAbsolute(pathValue) ? pathValue : resolve(cwd, pathValue);
    },
    async ensureParent(pathValue) { await mkdir(dirname(pathValue), { recursive: true }); },
    size: (pathValue) => existsSync(pathValue) ? statSync(pathValue).size : 0,
  };
}

function makeRigArgsRuntime() {
  const args = [];
  const builder = {
    raw(...values) { args.push(...values); return builder; },
    flag(name, enabled = true) { if (enabled) args.push(name); return builder; },
    value(name, value) { if (value !== undefined && value !== null) args.push(name, String(value)); return builder; },
    values(name, values) { for (const value of values ?? []) args.push(name, value); return builder; },
    toArray: () => [...args],
  };
  return builder;
}

function makeRigBoundedOutputCollector(maxBytes) {
  const chunks = [];
  let capturedBytes = 0;
  let truncated = false;
  const decodeUtf8Prefix = (buffer) => {
    const strictDecoder = new TextDecoder("utf-8", { fatal: true });
    for (let removed = 0; removed <= Math.min(3, buffer.byteLength); removed++) {
      try { return strictDecoder.decode(buffer.subarray(0, buffer.byteLength - removed)); }
      catch {}
    }
    return new TextDecoder().decode(buffer);
  };
  return {
    capture(buffer) {
      const remaining = Math.max(0, maxBytes - capturedBytes);
      if (remaining > 0) {
        const captured = buffer.subarray(0, remaining);
        chunks.push(captured);
        capturedBytes += captured.byteLength;
      }
      if (buffer.byteLength > remaining) truncated = true;
    },
    result() {
      const content = decodeUtf8Prefix(Buffer.concat(chunks, capturedBytes));
      return truncated ? content + "\\n[rig: output truncated]" : content;
    },
  };
}

function makeRigManagedProcess(child, command, timeoutMs) {
  let timedOut = false;
  let timeout;
  let escalation;
  let spawnError;
  const signal = (signalName) => {
    try {
      if (process.platform !== "win32" && child.pid) process.kill(-child.pid, signalName);
      else child.kill(signalName);
    } catch {}
  };
  const terminate = () => {
    timedOut = true;
    signal("SIGTERM");
    escalation = setTimeout(() => signal("SIGKILL"), 100);
  };
  return {
    async wait() {
      child.once("error", (error) => { spawnError = error; });
      timeout = setTimeout(terminate, timeoutMs);
      try {
        const exitCode = await new Promise((resolve) => child.once("close", (code) => resolve(code ?? 1)));
        if (spawnError) throw new Error("Command could not start: " + command[0] + ": " + spawnError.message);
        if (timedOut) throw new Error("Command timed out after " + timeoutMs + "ms.");
        return exitCode;
      } finally {
        if (timeout) clearTimeout(timeout);
        if (escalation) clearTimeout(escalation);
      }
    },
  };
}

function shellQuote(value) {
  if (/^[A-Za-z0-9_./:=@%+,-]+$/.test(value)) return value;
  return "'" + value.replaceAll("'", "'\\''") + "'";
}

function makeRigShellRuntime() {
  const renderTemplateValue = (value) => Array.isArray(value)
    ? value.map((item) => shellQuote(String(item))).join(" ")
    : shellQuote(String(value));
  const renderTemplateCommand = (strings, values) => strings.reduce(
    (command, part, index) => command + part + (index < values.length ? renderTemplateValue(values[index]) : ""),
    "",
  );
  const runProcess = async (args, options = {}, reportedCommand = args) => {
    const timeoutMs = options.timeoutMs ?? 30000;
    const maxOutputBytes = options.maxOutputBytes ?? 1048576;
    const child = spawn(args[0], args.slice(1), {
      cwd: options.cwd ?? process.cwd(),
      env: { ...process.env, ...options.env },
      stdio: ["ignore", "pipe", "pipe"],
      detached: process.platform !== "win32",
    });
    const stdout = makeRigBoundedOutputCollector(maxOutputBytes);
    const stderr = makeRigBoundedOutputCollector(maxOutputBytes);
    child.stdout.on("data", (chunk) => stdout.capture(chunk));
    child.stderr.on("data", (chunk) => stderr.capture(chunk));
    const exitCode = await makeRigManagedProcess(child, reportedCommand, timeoutMs).wait();
    return { command: reportedCommand, stdout: stdout.result(), stderr: stderr.result(), exitCode };
  };
  const exec = async (args, options = {}) => {
    if (!Array.isArray(args) || args.length === 0 || args.some((arg) => typeof arg !== "string" || arg.length === 0)) {
      throw new Error("shell.exec expects a non-empty array of command arguments.");
    }
    return runProcess(args, options);
  };
  const bash = (command, options = {}) => runProcess(["bash", "-lc", command], options, [command]);
  return {
    exec,
    bash,
    $: (strings, ...values) => bash(renderTemplateCommand(strings, values)),
    async json(args, options = {}) {
      const result = await exec(args, options);
      if (result.exitCode !== 0) throw new Error("Command failed before JSON could be parsed.");
      return JSON.parse(result.stdout);
    },
  };
}

const rigShell = makeRigShellRuntime();

async function runRigCommand(options) {
  const id = options.tool ? options.tool + "." + options.command : options.command;
  if (!/^[A-Za-z0-9_-]+[.][A-Za-z0-9_-]+$/.test(id)) throw new Error("Command id must use <tool>.<command>: " + id);
  if (options.input !== undefined && options.args?.length) throw new Error("Use input or args, not both.");
  const args = ["rig", "run", id];
  if (options.input !== undefined) args.push("--input", JSON.stringify(options.input));
  if (options.dryRun) args.push("--dry-run");
  args.push(...(options.args ?? []));
  const result = await rigShell.exec(args);
  if (result.exitCode !== 0) throw new Error("Rig tool command failed: " + id + "\\n" + result.stderr);
  const envelope = JSON.parse(result.stdout);
  if (envelope.errors?.length) throw new Error("Rig tool command failed: " + id + "\\n" + JSON.stringify(envelope.errors, null, 2));
  return envelope.data;
}

export const rig: RigToolKit = {
  z,
  defineTool: (definition) => typeof definition.commands === "function"
    ? { ...definition, commands: definition.commands((command) => command) }
    : definition,
  defineCommand: (definition) => definition,
  run: runRigCommand,
  $: (strings, ...values) => rigShell.$(strings, ...values),
  args: makeRigArgsRuntime,
  paths: makeRigPathRuntime(),
  shell: rigShell,
} as unknown as RigToolKit;

function defineToolRuntime<T extends RigToolDefinition | RigToolFactory>(value: T): T {
  return typeof value === "function" ? value : rig.defineTool(value as RigToolDefinition) as T;
}

export const RigTool = { define: defineToolRuntime };
`;
