export const RuntimeTypesSource = `// Generated by Rig. Safe to overwrite.
import type { Database } from "bun:sqlite";
import type { z } from "zod";

export type RigSchema = z.ZodTypeAny;

export type RigCollectionDefinition<T extends z.ZodObject<any> = z.ZodObject<any>> = {
  schema?: T;
  generateId?: (data: z.input<T>) => string;
};

export type RigCollectionEntry<T = Record<string, unknown>> = {
  id: string;
  data: T;
  body: string;
  createdAt: string;
  updatedAt: string;
};

export type RigCollectionHandle<T = Record<string, unknown>> = {
  readonly name: string;
  readonly path: string;
  create(entry: { id?: string; data: T; body?: string }): Promise<RigCollectionEntry<T>>;
  getEntry(id: string): Promise<RigCollectionEntry<T> | null>;
  update(id: string, patch: { data?: Partial<T>; body?: string }): Promise<RigCollectionEntry<T>>;
  upsert(entry: { id: string; data: T; body?: string }): Promise<{ id: string; created: boolean }>;
  remove(id: string): Promise<boolean>;
  list(options?: { where?: Record<string, unknown>; sort?: string; limit?: number; offset?: number }): Promise<{ entries: RigCollectionEntry<T>[]; total: number }>;
  search(query: string, options?: { limit?: number }): Promise<{ entries: Array<RigCollectionEntry<T> & { snippet: string; rank: number }> }>;
  count(where?: Record<string, unknown>): Promise<number>;
  getCollection(filter?: (entry: RigCollectionEntry<T>) => boolean): Promise<RigCollectionEntry<T>[]>;
  clear(): Promise<void>;
};

export type RigToolCollectionDefinitions = Record<string, RigCollectionDefinition>;

export type RigToolCollectionHandles<Collections extends RigToolCollectionDefinitions> = {
  [Name in keyof Collections]: Collections[Name] extends RigCollectionDefinition<infer Schema>
    ? RigCollectionHandle<z.output<Schema>>
    : RigCollectionHandle;
};

export type RigShellOptions = {
  cwd?: string;
  env?: Record<string, string | undefined>;
  timeoutMs?: number;
  maxOutputBytes?: number;
};

export type RigShellResult = {
  command: string[];
  stdout: string;
  stderr: string;
  exitCode: number;
};

export type RigShell = {
  $(strings: TemplateStringsArray, ...values: unknown[]): Promise<RigShellResult>;
  exec(args: string[], options?: RigShellOptions): Promise<RigShellResult>;
  bash(command: string, options?: RigShellOptions): Promise<RigShellResult>;
  json(args: string[], options?: RigShellOptions): Promise<unknown>;
};

export type RigPathHelper = {
  home(): string;
  resolve(cwd: string, pathValue: string): string;
  ensureParent(pathValue: string): Promise<void>;
  size(pathValue: string): number;
};

export type RigArgBuilder = {
  raw(...values: string[]): RigArgBuilder;
  flag(name: string, enabled?: boolean): RigArgBuilder;
  value(name: string, value: string | number | boolean | undefined | null): RigArgBuilder;
  values(name: string, values: string[] | undefined): RigArgBuilder;
  toArray(): string[];
};

export type RigRunOptions = {
  tool?: string;
  command: string;
  input?: unknown;
  args?: string[];
  dryRun?: boolean;
};

export type RigToolDatabase = Database & {
  readonly path: string;
  migrate(version: number, name: string, sql: string): void;
};

export type RigToolKvStore = {
  readonly path: string;
  get<T = unknown>(key: string): T | undefined;
  set(key: string, value: unknown): void;
};

export type RigCacheKey = readonly unknown[];

export type RigCacheQueryOptions<T> = {
  queryKey: RigCacheKey;
  queryFn: () => T | Promise<T>;
  /** Cached values younger than this duration return immediately; missing or stale values refresh before returning. */
  staleTime?: number;
};

export type RigToolCache = {
  readonly path: string;
  query<T>(options: RigCacheQueryOptions<T>): Promise<T>;
  peek<T = unknown>(queryKey: RigCacheKey): T | undefined;
  set<T>(queryKey: RigCacheKey, value: T): void;
  invalidate(queryKey: RigCacheKey): void;
  remove(queryKey: RigCacheKey): void;
  clear(): void;
};

export type RigLogMethod = {
  (message: string): void;
  (bindings: Record<string, unknown>, message?: string): void;
  (error: Error, message?: string): void;
};

export type RigToolLogger = {
  trace: RigLogMethod;
  debug: RigLogMethod;
  info: RigLogMethod;
  warn: RigLogMethod;
  error: RigLogMethod;
  fatal: RigLogMethod;
  child(bindings: Record<string, unknown>): RigToolLogger;
};

export type RigToolRunContext<
  Input,
  Env = unknown,
  Collections = Record<string, RigCollectionHandle>,
> = {
  input: Input;
  env: Env;
  processEnv: NodeJS.ProcessEnv;
  cwd: string;
  db: RigToolDatabase;
  kv: RigToolKvStore;
  cache: RigToolCache;
  log: RigToolLogger;
  rig: RigToolKit;
  collections: Collections;
};

export type RigToolExample<Input = any, Output = any> = {
  title: string;
  text: string;
  input?: Input;
  output?: Output;
};

export type RigCommandDefinition<
  Input extends RigSchema = RigSchema,
  Output extends RigSchema = RigSchema,
  Env = unknown,
  Collections = Record<string, RigCollectionHandle>,
> = {
  description: string;
  input: Input;
  output: Output;
  examples?: RigToolExample<z.input<Input>, z.output<Output>>[];
  run: (ctx: RigToolRunContext<z.output<Input>, Env, Collections>) => z.input<Output> | Promise<z.input<Output>>;
};

export type RigToolCommandBuilder<
  Env,
  Collections,
> = <Input extends RigSchema, Output extends RigSchema>(
  definition: RigCommandDefinition<Input, Output, Env, Collections>,
) => RigCommandDefinition<Input, Output, Env, Collections>;

export type RigToolCommandMap = Record<string, RigCommandDefinition<any, any, any, any>>;

export type RigToolCommandsFactory<
  Env,
  Collections,
  Commands extends RigToolCommandMap,
> = (command: RigToolCommandBuilder<Env, Collections>) => Commands;

export type RigToolDefinition<
  Env extends RigSchema = RigSchema,
  Collections extends RigToolCollectionDefinitions = RigToolCollectionDefinitions,
  Commands extends RigToolCommandMap = RigToolCommandMap,
> = {
  name?: string;
  description: string;
  env?: Env;
  setupDb?: (db: RigToolDatabase) => void | Promise<void>;
  collections?: Collections;
  commands:
    | Commands
    | RigToolCommandsFactory<z.output<Env>, RigToolCollectionHandles<Collections>, Commands>;
};

export type RigNormalizedToolDefinition<
  Env extends RigSchema = RigSchema,
  Collections extends RigToolCollectionDefinitions = RigToolCollectionDefinitions,
  Commands extends RigToolCommandMap = RigToolCommandMap,
> = Omit<RigToolDefinition<Env, Collections, Commands>, "commands"> & {
  commands: Commands;
};

export type RigToolKit = {
  z: typeof z;
  defineTool<
    Env extends RigSchema = RigSchema,
    Collections extends RigToolCollectionDefinitions = RigToolCollectionDefinitions,
    const Commands extends RigToolCommandMap = RigToolCommandMap,
  >(definition: RigToolDefinition<Env, Collections, Commands>): RigNormalizedToolDefinition<Env, Collections, Commands>;
  defineCommand<I extends RigSchema, O extends RigSchema>(definition: RigCommandDefinition<I, O>): RigCommandDefinition<I, O>;
  run<T = unknown>(options: RigRunOptions): Promise<T>;
  $(strings: TemplateStringsArray, ...values: unknown[]): Promise<RigShellResult>;
  args(): RigArgBuilder;
  paths: RigPathHelper;
  shell: RigShell;
};

export type RigToolFactory = (rig: RigToolKit) => RigToolDefinition<any, any, any> | Promise<RigToolDefinition<any, any, any>>;
`;
