import { afterEach, describe, expect, test } from "vitest";
import { existsSync } from "node:fs";
import { mkdtemp, readFile, rm, writeFile, mkdir } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { RigConfigStore } from "./config";
import {
  RigDirectoryMigrationService,
  RigHomeDirectoryMigrationPromptId,
  RigMigrationPromptStore,
} from "./migration";
import { RigPaths } from "./paths";

class TestHomeStore {
  private readonly homes: string[] = [];

  async create(): Promise<string> {
    const home = await mkdtemp(join(tmpdir(), "rig-test-home-"));
    this.homes.push(home);
    return home;
  }

  async cleanup(): Promise<void> {
    await Promise.all(
      this.homes.splice(0).map((home) => rm(home, { recursive: true, force: true })),
    );
  }
}

const homes = new TestHomeStore();

afterEach(async () => {
  await homes.cleanup();
});

describe("config", () => {
  test("expands tilde paths", async () => {
    const home = await homes.create();
    const paths = new RigPaths({ homeDir: home });
    expect(paths.expandTilde("~/rig/tools")).toBe(join(home, "rig/tools"));
    expect(paths.legacyRigDir).toBe(join(home, ".rig"));
    expect(paths.legacyDefaultBaseRegistryDir).toBe("~/.rig/tools");
    expect(paths.migrationPromptStatePath).toBe(join(home, "rig", "migration-prompts.json"));
  });

  test("creates first-run config and base registry in a temp home", async () => {
    const home = await homes.create();
    const paths = new RigPaths({ homeDir: home });
    const store = new RigConfigStore({ homeDir: home });
    const config = await store.ensure();
    expect(config.version).toBe(1);
    expect(store.migrationResult()).toBeUndefined();
    expect(existsSync(paths.configPath)).toBe(true);
    expect(existsSync(join(home, "rig/tools"))).toBe(true);
    expect(existsSync(join(home, "rig/tools/tsconfig.json"))).toBe(true);
    expect(existsSync(join(home, "rig/runtime/sdk.ts"))).toBe(true);
    expect(existsSync(join(home, "rig/runtime/globals.d.ts"))).toBe(true);
  });

  test("migrates legacy .rig state to the visible rig folder", async () => {
    const home = await homes.create();
    const legacyDir = join(home, ".rig");
    await mkdir(join(legacyDir, "tools", "legacy"), { recursive: true });
    await writeFile(
      join(legacyDir, "rig.json"),
      `${JSON.stringify({ version: 1, baseRegistryDir: "~/.rig/tools", customRegistries: [] })}\n`,
      "utf8",
    );
    await writeFile(join(legacyDir, "tools", "legacy", "index.rig.ts"), "export default {};\n");

    const store = new RigConfigStore({ homeDir: home });
    const config = await store.ensure();

    expect(store.migrationResult()).toMatchObject({
      promptId: RigHomeDirectoryMigrationPromptId,
      status: "migrated",
      legacyDir,
      currentDir: join(home, "rig"),
      configUpdated: true,
    });
    expect(config.baseRegistryDir).toBe("~/rig/tools");
    expect(existsSync(legacyDir)).toBe(false);
    expect(existsSync(join(home, "rig", "tools", "legacy", "index.rig.ts"))).toBe(true);
    expect(await readFile(join(home, "rig", "rig.json"), "utf8")).toContain("~/rig/tools");
  });

  test("replaces a generated default rig folder during legacy migration", async () => {
    const home = await homes.create();
    const legacyDir = join(home, ".rig");
    await mkdir(join(legacyDir, "tools", "legacy"), { recursive: true });
    await writeFile(
      join(legacyDir, "rig.json"),
      `${JSON.stringify({ version: 1, baseRegistryDir: "~/custom-tools", customRegistries: [] })}\n`,
      "utf8",
    );
    await mkdir(join(home, "rig", "tools"), { recursive: true });
    await writeFile(
      join(home, "rig", "rig.json"),
      `${JSON.stringify({
        version: 1,
        baseRegistryDir: "~/rig/tools",
        customRegistries: [],
        cronJobs: [],
      })}\n`,
      "utf8",
    );
    await writeFile(join(home, "rig", "tools", "tsconfig.json"), "// Generated by Rig.\n");
    await mkdir(join(home, "rig", "cron"));
    await writeFile(join(home, "rig", "update-check.json"), "{}\n");
    await writeFile(join(home, "rig", "migration-prompts.json"), "{}\n");

    const store = new RigConfigStore({ homeDir: home });
    const config = await store.ensure();

    expect(store.migrationResult()).toMatchObject({ status: "migrated", configUpdated: false });
    expect(config.baseRegistryDir).toBe("~/custom-tools");
    expect(existsSync(join(home, "rig", "tools", "legacy"))).toBe(true);
  });

  test("leaves legacy state in place when the new rig folder has user data", async () => {
    const home = await homes.create();
    const legacyDir = join(home, ".rig");
    await mkdir(join(legacyDir, "tools", "legacy"), { recursive: true });
    await writeFile(
      join(legacyDir, "rig.json"),
      `${JSON.stringify({ version: 1, baseRegistryDir: "~/.rig/tools", customRegistries: [] })}\n`,
      "utf8",
    );
    await mkdir(join(home, "rig", "tools", "current"), { recursive: true });
    await writeFile(
      join(home, "rig", "rig.json"),
      `${JSON.stringify({
        version: 1,
        baseRegistryDir: "~/rig/tools",
        customRegistries: [],
        cronJobs: [],
      })}\n`,
      "utf8",
    );

    const store = new RigConfigStore({ homeDir: home });
    const config = await store.ensure();

    expect(store.migrationResult()).toMatchObject({
      promptId: RigHomeDirectoryMigrationPromptId,
      status: "manual",
      legacyDir,
      currentDir: join(home, "rig"),
      configUpdated: false,
    });
    expect(config.baseRegistryDir).toBe("~/rig/tools");
    expect(existsSync(legacyDir)).toBe(true);
    expect(existsSync(join(home, "rig", "tools", "current"))).toBe(true);

    await store.acknowledgeMigrationPrompt();
    const promptStatePath = new RigPaths({ homeDir: home }).migrationPromptStatePath;
    const promptState = await readFile(promptStatePath, "utf8");
    expect(promptState).toContain(RigHomeDirectoryMigrationPromptId);
    await store.acknowledgeMigrationPrompt();
    expect(await readFile(promptStatePath, "utf8")).toBe(promptState);

    const nextStore = new RigConfigStore({ homeDir: home });
    await expect(nextStore.ensure()).resolves.toMatchObject({ baseRegistryDir: "~/rig/tools" });
    expect(nextStore.migrationResult()).toBeUndefined();
    await nextStore.acknowledgeMigrationPrompt();
  });

  test("handles legacy migration edge cases conservatively", async () => {
    const emptyLegacyHome = await homes.create();
    await mkdir(join(emptyLegacyHome, ".rig"));
    await expect(
      new RigDirectoryMigrationService(
        new RigPaths({ homeDir: emptyLegacyHome }),
      ).migrateIfNeeded(),
    ).resolves.toBeUndefined();

    const toolsOnlyHome = await homes.create();
    await mkdir(join(toolsOnlyHome, ".rig", "tools", "legacy"), { recursive: true });
    await expect(
      new RigDirectoryMigrationService(new RigPaths({ homeDir: toolsOnlyHome })).migrateIfNeeded(),
    ).resolves.toMatchObject({ status: "migrated", configUpdated: false });
    expect(existsSync(join(toolsOnlyHome, "rig", "tools", "legacy"))).toBe(true);

    const invalidCurrentHome = await homes.create();
    await mkdir(join(invalidCurrentHome, ".rig", "tools"), { recursive: true });
    await mkdir(join(invalidCurrentHome, "rig"));
    await writeFile(join(invalidCurrentHome, "rig", "rig.json"), "{ nope", "utf8");
    await expect(
      new RigDirectoryMigrationService(
        new RigPaths({ homeDir: invalidCurrentHome }),
      ).migrateIfNeeded(),
    ).resolves.toMatchObject({ status: "manual" });

    const cronConflictHome = await homes.create();
    await mkdir(join(cronConflictHome, ".rig", "tools"), { recursive: true });
    await mkdir(join(cronConflictHome, "rig", "cron"), { recursive: true });
    await writeFile(
      join(cronConflictHome, "rig", "rig.json"),
      `${JSON.stringify({
        version: 1,
        baseRegistryDir: "~/rig/tools",
        customRegistries: [],
        cronJobs: [],
      })}\n`,
      "utf8",
    );
    await writeFile(join(cronConflictHome, "rig", "cron", "job.ts"), "// job\n", "utf8");
    await expect(
      new RigDirectoryMigrationService(
        new RigPaths({ homeDir: cronConflictHome }),
      ).migrateIfNeeded(),
    ).resolves.toMatchObject({ status: "manual" });

    const extraFileHome = await homes.create();
    await mkdir(join(extraFileHome, ".rig", "tools"), { recursive: true });
    await mkdir(join(extraFileHome, "rig"));
    await writeFile(
      join(extraFileHome, "rig", "rig.json"),
      `${JSON.stringify({
        version: 1,
        baseRegistryDir: "~/rig/tools",
        customRegistries: [],
        cronJobs: [],
      })}\n`,
      "utf8",
    );
    await writeFile(join(extraFileHome, "rig", "notes.txt"), "mine\n", "utf8");
    await expect(
      new RigDirectoryMigrationService(new RigPaths({ homeDir: extraFileHome })).migrateIfNeeded(),
    ).resolves.toMatchObject({ status: "manual" });

    const invalidPromptStateHome = await homes.create();
    const invalidPromptStatePaths = new RigPaths({ homeDir: invalidPromptStateHome });
    await mkdir(invalidPromptStatePaths.rigDir, { recursive: true });
    await writeFile(invalidPromptStatePaths.migrationPromptStatePath, "[]\n", "utf8");
    const promptStore = new RigMigrationPromptStore(invalidPromptStatePaths);
    await expect(promptStore.hasPrompted("custom-prompt")).resolves.toBe(false);
    await promptStore.markPrompted("custom-prompt");
    await expect(promptStore.hasPrompted("custom-prompt")).resolves.toBe(true);
  });
});
