import { afterEach, describe, expect, test } from "vite-plus/test";
import { spawn } from "node:child_process";
import { existsSync } from "node:fs";
import { mkdir, mkdtemp, readFile, readdir, rm, utimes, writeFile } from "node:fs/promises";
import { hostname, tmpdir } from "node:os";
import { join } from "node:path";
import { pathToFileURL } from "node:url";
import { RigConfigStoreClass } from "./config";
import {
  RigDirectoryMigrationServiceClass,
  RigHomeDirectoryMigrationPromptId,
  RigMigrationPromptStoreClass,
} from "./migration";
import { RigPathsClass } from "./paths";

class TestHomeStore {
  private readonly homes: string[] = [];

  async create(): Promise<string> {
    const home = await mkdtemp(join(tmpdir(), "rig-test-home-"));
    this.homes.push(home);
    return home;
  }

  async cleanup(): Promise<void> {
    await Promise.all(
      this.homes.splice(0).map((home) => rm(home, { recursive: true, force: true })),
    );
  }
}

const homes = new TestHomeStore();

afterEach(async () => {
  await homes.cleanup();
});

describe("config", () => {
  test("expands tilde paths", async () => {
    const home = await homes.create();
    const paths = new RigPathsClass({ homeDir: home });
    expect(paths.expandTilde("~/rig/tools")).toBe(join(home, "rig/tools"));
    expect(paths.legacyRigDir).toBe(join(home, ".rig"));
    expect(paths.legacyDefaultBaseRegistryDir).toBe("~/.rig/tools");
    expect(paths.migrationPromptStatePath).toBe(join(home, "rig", "migration-prompts.json"));
  });

  test("creates first-run config and base registry in a temp home", async () => {
    const home = await homes.create();
    const paths = new RigPathsClass({ homeDir: home });
    const store = new RigConfigStoreClass({ homeDir: home });
    const config = await store.ensure();
    expect(config.version).toBe(1);
    expect(store.migrationResult()).toBeUndefined();
    expect(existsSync(paths.configPath)).toBe(true);
    expect(existsSync(join(home, "rig/tools"))).toBe(true);
    expect(existsSync(join(home, "rig/tools/tsconfig.json"))).toBe(true);
    expect(existsSync(join(home, "rig/runtime/sdk.ts"))).toBe(true);
    expect(existsSync(join(home, "rig/runtime/globals.d.ts"))).toBe(true);
  });

  test("migrates legacy .rig state to the visible rig folder", async () => {
    const home = await homes.create();
    const legacyDir = join(home, ".rig");
    await mkdir(join(legacyDir, "tools", "legacy"), { recursive: true });
    await writeFile(
      join(legacyDir, "rig.json"),
      `${JSON.stringify({ version: 1, baseRegistryDir: "~/.rig/tools", customRegistries: [] })}\n`,
      "utf8",
    );
    await writeFile(join(legacyDir, "tools", "legacy", "index.rig.ts"), "export default {};\n");

    const store = new RigConfigStoreClass({ homeDir: home });
    const config = await store.ensure();

    expect(store.migrationResult()).toMatchObject({
      promptId: RigHomeDirectoryMigrationPromptId,
      status: "migrated",
      legacyDir,
      currentDir: join(home, "rig"),
      configUpdated: true,
    });
    expect(config.baseRegistryDir).toBe("~/rig/tools");
    expect(existsSync(legacyDir)).toBe(false);
    expect(existsSync(join(home, "rig", "tools", "legacy", "index.rig.ts"))).toBe(true);
    expect(await readFile(join(home, "rig", "rig.json"), "utf8")).toContain("~/rig/tools");
  });

  test("replaces a generated default rig folder during legacy migration", async () => {
    const home = await homes.create();
    const legacyDir = join(home, ".rig");
    await mkdir(join(legacyDir, "tools", "legacy"), { recursive: true });
    await writeFile(
      join(legacyDir, "rig.json"),
      `${JSON.stringify({ version: 1, baseRegistryDir: "~/custom-tools", customRegistries: [] })}\n`,
      "utf8",
    );
    await mkdir(join(home, "rig", "tools"), { recursive: true });
    await writeFile(
      join(home, "rig", "rig.json"),
      `${JSON.stringify({
        version: 1,
        baseRegistryDir: "~/rig/tools",
        customRegistries: [],
        cronJobs: [],
      })}\n`,
      "utf8",
    );
    await writeFile(join(home, "rig", "tools", "tsconfig.json"), "// Generated by Rig.\n");
    await mkdir(join(home, "rig", "cron"));
    await writeFile(join(home, "rig", "update-check.json"), "{}\n");
    await writeFile(join(home, "rig", "migration-prompts.json"), "{}\n");

    const store = new RigConfigStoreClass({ homeDir: home });
    const config = await store.ensure();

    expect(store.migrationResult()).toMatchObject({ status: "migrated", configUpdated: false });
    expect(config.baseRegistryDir).toBe("~/custom-tools");
    expect(existsSync(join(home, "rig", "tools", "legacy"))).toBe(true);
  });

  test("leaves legacy state in place when the new rig folder has user data", async () => {
    const home = await homes.create();
    const legacyDir = join(home, ".rig");
    await mkdir(join(legacyDir, "tools", "legacy"), { recursive: true });
    await writeFile(
      join(legacyDir, "rig.json"),
      `${JSON.stringify({ version: 1, baseRegistryDir: "~/.rig/tools", customRegistries: [] })}\n`,
      "utf8",
    );
    await mkdir(join(home, "rig", "tools", "current"), { recursive: true });
    await writeFile(
      join(home, "rig", "rig.json"),
      `${JSON.stringify({
        version: 1,
        baseRegistryDir: "~/rig/tools",
        customRegistries: [],
        cronJobs: [],
      })}\n`,
      "utf8",
    );

    const store = new RigConfigStoreClass({ homeDir: home });
    const config = await store.ensure();

    expect(store.migrationResult()).toMatchObject({
      promptId: RigHomeDirectoryMigrationPromptId,
      status: "manual",
      legacyDir,
      currentDir: join(home, "rig"),
      configUpdated: false,
    });
    expect(config.baseRegistryDir).toBe("~/rig/tools");
    expect(existsSync(legacyDir)).toBe(true);
    expect(existsSync(join(home, "rig", "tools", "current"))).toBe(true);

    await store.acknowledgeMigrationPrompt();
    const promptStatePath = new RigPathsClass({ homeDir: home }).migrationPromptStatePath;
    const promptState = await readFile(promptStatePath, "utf8");
    expect(promptState).toContain(RigHomeDirectoryMigrationPromptId);
    await store.acknowledgeMigrationPrompt();
    expect(await readFile(promptStatePath, "utf8")).toBe(promptState);

    const nextStore = new RigConfigStoreClass({ homeDir: home });
    await expect(nextStore.ensure()).resolves.toMatchObject({ baseRegistryDir: "~/rig/tools" });
    expect(nextStore.migrationResult()).toBeUndefined();
    await nextStore.acknowledgeMigrationPrompt();
  });

  test("handles legacy migration edge cases conservatively", async () => {
    const emptyLegacyHome = await homes.create();
    await mkdir(join(emptyLegacyHome, ".rig"));
    await expect(
      new RigDirectoryMigrationServiceClass(
        new RigPathsClass({ homeDir: emptyLegacyHome }),
      ).migrateIfNeeded(),
    ).resolves.toBeUndefined();

    const toolsOnlyHome = await homes.create();
    await mkdir(join(toolsOnlyHome, ".rig", "tools", "legacy"), { recursive: true });
    await expect(
      new RigDirectoryMigrationServiceClass(
        new RigPathsClass({ homeDir: toolsOnlyHome }),
      ).migrateIfNeeded(),
    ).resolves.toMatchObject({ status: "migrated", configUpdated: false });
    expect(existsSync(join(toolsOnlyHome, "rig", "tools", "legacy"))).toBe(true);

    const invalidCurrentHome = await homes.create();
    await mkdir(join(invalidCurrentHome, ".rig", "tools"), { recursive: true });
    await mkdir(join(invalidCurrentHome, "rig"));
    await writeFile(join(invalidCurrentHome, "rig", "rig.json"), "{ nope", "utf8");
    await expect(
      new RigDirectoryMigrationServiceClass(
        new RigPathsClass({ homeDir: invalidCurrentHome }),
      ).migrateIfNeeded(),
    ).resolves.toMatchObject({ status: "manual" });

    const cronConflictHome = await homes.create();
    await mkdir(join(cronConflictHome, ".rig", "tools"), { recursive: true });
    await mkdir(join(cronConflictHome, "rig", "cron"), { recursive: true });
    await writeFile(
      join(cronConflictHome, "rig", "rig.json"),
      `${JSON.stringify({
        version: 1,
        baseRegistryDir: "~/rig/tools",
        customRegistries: [],
        cronJobs: [],
      })}\n`,
      "utf8",
    );
    await writeFile(join(cronConflictHome, "rig", "cron", "job.ts"), "// job\n", "utf8");
    await expect(
      new RigDirectoryMigrationServiceClass(
        new RigPathsClass({ homeDir: cronConflictHome }),
      ).migrateIfNeeded(),
    ).resolves.toMatchObject({ status: "manual" });

    const extraFileHome = await homes.create();
    await mkdir(join(extraFileHome, ".rig", "tools"), { recursive: true });
    await mkdir(join(extraFileHome, "rig"));
    await writeFile(
      join(extraFileHome, "rig", "rig.json"),
      `${JSON.stringify({
        version: 1,
        baseRegistryDir: "~/rig/tools",
        customRegistries: [],
        cronJobs: [],
      })}\n`,
      "utf8",
    );
    await writeFile(join(extraFileHome, "rig", "notes.txt"), "mine\n", "utf8");
    await expect(
      new RigDirectoryMigrationServiceClass(
        new RigPathsClass({ homeDir: extraFileHome }),
      ).migrateIfNeeded(),
    ).resolves.toMatchObject({ status: "manual" });

    const invalidPromptStateHome = await homes.create();
    const invalidPromptStatePaths = new RigPathsClass({ homeDir: invalidPromptStateHome });
    await mkdir(invalidPromptStatePaths.rigDir, { recursive: true });
    await writeFile(invalidPromptStatePaths.migrationPromptStatePath, "[]\n", "utf8");
    const promptStore = new RigMigrationPromptStoreClass(invalidPromptStatePaths);
    await expect(promptStore.hasPrompted("custom-prompt")).resolves.toBe(false);
    await promptStore.markPrompted("custom-prompt");
    await expect(promptStore.hasPrompted("custom-prompt")).resolves.toBe(true);
  });

  test("serializes same-process updates without lost config changes", async () => {
    const home = await homes.create();
    const paths = new RigPathsClass({ homeDir: home });
    await new RigConfigStoreClass({ homeDir: home }).ensure();

    await Promise.all(
      Array.from({ length: 20 }, (_, index) =>
        new RigConfigStoreClass({ homeDir: home }).update(async (config) => {
          await new Promise((resolve) => setTimeout(resolve, 1));
          return {
            ...config,
            customRegistries: [...config.customRegistries, `registry-${index}`],
          };
        }),
      ),
    );

    const config = await new RigConfigStoreClass({ homeDir: home }).read();
    expect(config.customRegistries.toSorted()).toEqual(
      Array.from({ length: 20 }, (_, index) => `registry-${index}`).toSorted(),
    );
    expect((await readdir(paths.rigDir)).filter((entry) => entry.includes(".tmp-"))).toEqual([]);
    expect(existsSync(`${paths.configPath}.lock`)).toBe(false);
  });

  test("serializes disposable-process updates without temp collisions or lost changes", async () => {
    const home = await homes.create();
    const paths = new RigPathsClass({ homeDir: home });
    await new RigConfigStoreClass({ homeDir: home }).ensure();
    const configModule = pathToFileURL(join(process.cwd(), "src", "config", "config.ts")).href;
    const script = `
import { RigConfigStoreClass } from ${JSON.stringify(configModule)};
const store = new RigConfigStoreClass({ homeDir: process.env.RIG_CONCURRENCY_HOME });
await store.update(async (config) => {
  await Bun.sleep(5);
  return { ...config, customRegistries: [...config.customRegistries, process.env.RIG_CONCURRENCY_ID] };
});
`;

    const processes = Array.from({ length: 8 }, (_, index) =>
      spawn("bun", ["--eval", script], {
        cwd: process.cwd(),
        env: {
          ...process.env,
          RIG_CONCURRENCY_HOME: home,
          RIG_CONCURRENCY_ID: `process-${index}`,
        },
      }),
    );
    const results = await Promise.all(
      processes.map(
        (child) =>
          new Promise<{ exitCode: number; stderr: string }>((resolve) => {
            let stderr = "";
            child.stderr.setEncoding("utf8");
            child.stderr.on("data", (chunk: string) => {
              stderr += chunk;
            });
            child.on("close", (code) => resolve({ exitCode: code ?? 1, stderr }));
          }),
      ),
    );

    expect(results).toEqual(results.map(() => ({ exitCode: 0, stderr: "" })));
    const config = await new RigConfigStoreClass({ homeDir: home }).read();
    expect(config.customRegistries.toSorted()).toEqual(
      Array.from({ length: 8 }, (_, index) => `process-${index}`).toSorted(),
    );
    expect((await readdir(paths.rigDir)).filter((entry) => entry.includes(".tmp-"))).toEqual([]);
    expect(existsSync(`${paths.configPath}.lock`)).toBe(false);
  });

  test("times out on a live lock and recovers a stale dead-owner lock", async () => {
    const home = await homes.create();
    const paths = new RigPathsClass({ homeDir: home });
    await new RigConfigStoreClass({ homeDir: home }).ensure();
    const lockPath = `${paths.configPath}.lock`;
    const ownerPath = join(lockPath, "owner.json");
    await mkdir(lockPath);
    await writeFile(
      ownerPath,
      `${JSON.stringify({
        token: "live",
        pid: process.pid,
        hostname: hostname(),
        acquiredAt: new Date(0).toISOString(),
      })}\n`,
      "utf8",
    );
    await utimes(lockPath, new Date(0), new Date(0));

    const boundedStore = new RigConfigStoreClass({
      homeDir: home,
      configLock: { timeoutMs: 30, retryMs: 5, staleMs: 1 },
    });
    await expect(boundedStore.update((config) => config)).rejects.toThrow(
      "Timed out waiting for lock",
    );

    await writeFile(
      ownerPath,
      `${JSON.stringify({
        token: "dead",
        pid: 2_147_483_647,
        hostname: hostname(),
        acquiredAt: new Date(0).toISOString(),
      })}\n`,
      "utf8",
    );
    await utimes(lockPath, new Date(0), new Date(0));
    await expect(
      boundedStore.update((config) => ({
        ...config,
        customRegistries: [...config.customRegistries, "recovered"],
      })),
    ).resolves.toMatchObject({ customRegistries: ["recovered"] });
    expect(existsSync(lockPath)).toBe(false);
  });

  test("releases the lock when a mutator fails", async () => {
    const home = await homes.create();
    const paths = new RigPathsClass({ homeDir: home });
    const store = new RigConfigStoreClass({ homeDir: home });
    const original = await store.ensure();

    await expect(
      store.update(() => {
        throw new Error("mutator failed");
      }),
    ).rejects.toThrow("mutator failed");
    expect(await store.read()).toEqual(original);
    expect(existsSync(`${paths.configPath}.lock`)).toBe(false);
    await expect(
      store.update((config) => ({ ...config, customRegistries: ["after-failure"] })),
    ).resolves.toMatchObject({ customRegistries: ["after-failure"] });
  });

  test("initializes config through update when ensure was not called", async () => {
    const home = await homes.create();
    const store = new RigConfigStoreClass({ homeDir: home });

    await expect(
      store.update((config) => ({ ...config, customRegistries: ["initialized-by-update"] })),
    ).resolves.toMatchObject({
      version: 1,
      baseRegistryDir: "~/rig/tools",
      customRegistries: ["initialized-by-update"],
    });
  });

  test("serializes concurrent migration prompt updates", async () => {
    const home = await homes.create();
    const paths = new RigPathsClass({ homeDir: home });
    const store = new RigMigrationPromptStoreClass(paths);
    const promptIds = Array.from({ length: 12 }, (_, index) => `prompt-${index}`);

    await Promise.all(promptIds.map((promptId) => store.markPrompted(promptId)));

    await expect(
      Promise.all(promptIds.map((promptId) => store.hasPrompted(promptId))),
    ).resolves.toEqual(promptIds.map(() => true));
    expect(existsSync(`${paths.migrationPromptStatePath}.lock`)).toBe(false);
    expect((await readdir(paths.rigDir)).filter((entry) => entry.includes(".tmp-"))).toEqual([]);
  });
});
