import { readFile, writeFile } from "node:fs/promises";
import type { ConfigOptions } from "../config/config";
import { ToolDiscoveryService } from "../registry/discover";

export type ToolRuntimeCommentUpdate = {
  name: string;
  path: string;
  changed: boolean;
};

export type ToolRuntimeCommentSyncResult = {
  tools: ToolRuntimeCommentUpdate[];
};

const StartMarker = "// rig:runtime-reference:start";
const EndMarker = "// rig:runtime-reference:end";

const RuntimeReference = `Generated by Rig. This block is refreshed automatically.

Rig tool runtime:
- Export a default \`RigToolFactory\`: \`const tool: RigToolFactory = (rig) => rig.defineTool({ ... }); export default tool;\`.
- \`rig.z\` is Zod.
- \`rig.defineTool(definition)\` defines the tool.
- \`rig.command(definition)\` defines one command.
- \`rig.input(shapeOrSchema)\` validates command input.
- \`rig.output(shapeOrSchema)\` validates command output.
- \`rig.args()\` builds argv arrays with \`.raw()\`, \`.flag()\`, \`.value()\`, \`.values()\`, and \`.toArray()\`.
- \`rig.paths.home()\`, \`rig.paths.resolve(cwd, path)\`, \`rig.paths.ensureParent(path)\`, and \`rig.paths.size(path)\` cover common path work.
- \`rig.shell.$\` runs a Bun-style tagged template command.
- \`rig.shell.exec(args, options)\` runs a command from an argv array.
- \`rig.shell.bash(command, options)\` runs a bash command.
- \`rig.shell.json(args, options)\` runs a command and parses JSON stdout.

Command run context:
- Use \`run: async (context) => { ... }\`. Do not destructure the context object in examples.
- \`context.input\` is already validated by the input schema.
- \`context.env\` is the process environment.
- \`context.cwd\` is the current working directory.
- \`context.rig\` exposes the same helper API as the top-level \`rig\` tool factory argument.
- Return a value that matches the output schema.

Shell and bash execution:
- Prefer \`context.rig.shell\` for local command execution.
- Bun-style template execution: await context.rig.shell.$\`echo hello\`.
- Run bash with \`await context.rig.shell.bash("echo hello", { cwd: context.cwd, timeoutMs: 30_000 })\`.
- Parse JSON stdout with \`await context.rig.shell.json(["bash", "-lc", "jq -n '{ok:true}'"])\`.
- \`context.rig.shell.exec\` and \`context.rig.shell.bash\` return \`{ command, stdout, stderr, exitCode }\`.
- Build argv safely with \`context.rig.args().raw("git", "status").flag("--short").toArray()\`.
`;

export class ToolRuntimeCommentSyncService {
  private readonly discovery: ToolDiscoveryService;

  constructor(options: ConfigOptions = {}) {
    this.discovery = new ToolDiscoveryService(options);
  }

  async sync(): Promise<ToolRuntimeCommentSyncResult> {
    const tools = await this.discovery.discover();
    const updates = await Promise.all(
      tools.map(async (tool) => ({
        name: tool.name,
        path: tool.toolPath,
        changed: await this.updateFile(tool.toolPath),
      })),
    );
    return { tools: updates };
  }

  renderPrefix(): string {
    return [
      StartMarker,
      ...RuntimeReference.trimEnd()
        .split("\n")
        .map((line) => (line ? `// ${line}` : "//")),
      EndMarker,
    ].join("\n");
  }

  upsertPrefix(source: string): string {
    const withoutExisting = source.replace(this.managedBlockPattern(), "").trimStart();
    const shebang = withoutExisting.match(/^(#!.*\n)/);
    const prefix = this.renderPrefix();
    const body = shebang ? withoutExisting.slice(shebang[0].length).trimStart() : withoutExisting;
    const next = [prefix, body.trimEnd()].filter(Boolean).join("\n\n");
    return `${shebang?.[0] ?? ""}${next}\n`;
  }

  private async updateFile(path: string): Promise<boolean> {
    const existing = await readFile(path, "utf8");
    const next = this.upsertPrefix(existing);
    if (next === existing) return false;
    await writeFile(path, next, "utf8");
    return true;
  }

  private managedBlockPattern(): RegExp {
    return new RegExp(
      `${this.escapeRegExp(StartMarker)}[\\s\\S]*?${this.escapeRegExp(EndMarker)}\\n*`,
    );
  }

  private escapeRegExp(value: string): string {
    return value.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
  }
}
