import { readFile, writeFile } from "node:fs/promises";
import type { ConfigOptions } from "../config/config";
import { ToolDiscoveryService } from "../registry/discover";

type BunFileApi = {
  file(path: string): { text(): Promise<string> };
  write(path: string, content: string): Promise<number>;
};

export type ToolRuntimeCommentUpdate = {
  name: string;
  path: string;
  changed: boolean;
};

export type ToolRuntimeCommentSyncResult = {
  tools: ToolRuntimeCommentUpdate[];
};

const StartMarker = "// rig:runtime-reference:start";
const EndMarker = "// rig:runtime-reference:end";

const RuntimeReference = `Generated by Rig. This block is refreshed automatically.

Rig tool runtime:
- Export a default \`RigToolFactory\`: \`const tool: RigToolFactory = (rig) => rig.defineTool({ ... }); export default tool;\`.
- \`rig.z\` is Zod. Docs: https://zod.dev/
- \`rig.defineTool(definition)\` defines the tool.
- \`rig.command(definition)\` defines one command.
- \`rig.input(shapeOrSchema)\` validates command input.
- \`rig.output(shapeOrSchema)\` validates command output.
- \`rig.run({ command: "tool.command", input })\` runs another registered Rig command and returns its data.
- \`rig.$\` runs a Bun Shell tagged template command with escaped interpolations. Docs: https://bun.com/docs/runtime/shell
- \`rig.args()\` builds argv arrays with \`.raw()\`, \`.flag()\`, \`.value()\`, \`.values()\`, and \`.toArray()\`.
- \`rig.paths.home()\`, \`rig.paths.resolve(cwd, path)\`, \`rig.paths.ensureParent(path)\`, and \`rig.paths.size(path)\` cover common path work.

Command run context:
- Use \`run: async (context) => { ... }\`. Do not destructure the context object in examples.
- \`context.input\` is already validated by the input schema.
- \`context.env\` is the process environment.
- \`context.cwd\` is the current working directory.
- Return a value that matches the output schema.
`;

export class ToolRuntimeCommentSyncService {
  private readonly discovery: ToolDiscoveryService;

  constructor(options: ConfigOptions = {}) {
    this.discovery = new ToolDiscoveryService(options);
  }

  async sync(): Promise<ToolRuntimeCommentSyncResult> {
    const tools = await this.discovery.discover();
    const updates = await Promise.all(
      tools.map(async (tool) => ({
        name: tool.name,
        path: tool.toolPath,
        changed: await this.updateFile(tool.toolPath),
      })),
    );
    return { tools: updates };
  }

  renderPrefix(): string {
    return [
      StartMarker,
      ...RuntimeReference.trimEnd()
        .split("\n")
        .map((line) => (line ? `// ${line}` : "//")),
      EndMarker,
    ].join("\n");
  }

  upsertPrefix(source: string): string {
    const withoutExisting = source.replace(this.managedBlockPattern(), "").trimStart();
    const shebang = withoutExisting.match(/^(#!.*\n)/);
    const prefix = this.renderPrefix();
    const body = shebang ? withoutExisting.slice(shebang[0].length).trimStart() : withoutExisting;
    const next = [prefix, body.trimEnd()].filter(Boolean).join("\n\n");
    return `${shebang?.[0] ?? ""}${next}\n`;
  }

  private async updateFile(path: string): Promise<boolean> {
    const existing = await this.readText(path);
    const next = this.upsertPrefix(existing);
    if (next === existing) return false;
    await this.writeText(path, next);
    return true;
  }

  private async readText(path: string): Promise<string> {
    const bun = this.bunFileApi();
    /* v8 ignore next */
    if (bun) return bun.file(path).text();
    return readFile(path, "utf8");
  }

  private async writeText(path: string, content: string): Promise<void> {
    const bun = this.bunFileApi();
    /* v8 ignore next 4 */
    if (bun) {
      await bun.write(path, content);
      return;
    }
    await writeFile(path, content, "utf8");
  }

  private bunFileApi(): BunFileApi | undefined {
    const candidate = (globalThis as typeof globalThis & { Bun?: Partial<BunFileApi> }).Bun;
    /* v8 ignore next 3 */
    if (typeof candidate?.file === "function" && typeof candidate.write === "function") {
      return candidate as BunFileApi;
    }
    return undefined;
  }

  private managedBlockPattern(): RegExp {
    return new RegExp(
      `${this.escapeRegExp(StartMarker)}[\\s\\S]*?${this.escapeRegExp(EndMarker)}\\n*`,
    );
  }

  private escapeRegExp(value: string): string {
    return value.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
  }
}
