import { readFile, writeFile } from "node:fs/promises";
import type { ConfigOptions } from "../config/config";
import { ToolDiscoveryService } from "../registry/discover";

type BunFileApi = {
  file(path: string): { text(): Promise<string> };
  write(path: string, content: string): Promise<number>;
};

export type ToolRuntimeCommentUpdate = {
  name: string;
  path: string;
  changed: boolean;
};

export type ToolRuntimeCommentSyncResult = {
  tools: ToolRuntimeCommentUpdate[];
};

const StartMarker = "// rig:runtime-reference:start";
const EndMarker = "// rig:runtime-reference:end";

const RuntimeReference = `Generated by Rig. This block is refreshed automatically.

Rig tool runtime:
- Export a default \`RigToolFactory\`: \`const tool: RigToolFactory = (rig) => rig.defineTool({ ... }); export default tool;\`.
- \`rig.z\` is Zod. Docs: https://zod.dev/
- \`rig.defineTool(definition)\` defines the tool.
- \`rig.defineCommand(definition)\` defines one command with \`{ description, input, output, run }\`.
- Use \`rig.z.object({ ... })\` for input/output schemas.
- \`rig.run({ command: "tool.command", input })\` runs another registered Rig command and returns its data.
- \`rig.$\` runs a Bun Shell tagged template command with escaped interpolations. Docs: https://bun.com/docs/runtime/shell
- \`rig.args()\` builds argv arrays with \`.raw()\`, \`.flag()\`, \`.value()\`, \`.values()\`, and \`.toArray()\`.
- \`rig.paths.home()\`, \`rig.paths.resolve(cwd, path)\`, \`rig.paths.ensureParent(path)\`, and \`rig.paths.size(path)\` cover common path work.
- Add \`env: rig.z.object({ KEY: rig.z.string() })\` to validate a \`.env\` file beside the tool entry file and receive parsed values on \`context.env\`.

Tool logging and key-value state:
- Use \`context.log.info(...)\`, \`context.log.warn(...)\`, or another Pino-style method for structured logs with a default \`tool:<tool>.<command>\` prefix.
- Rig writes app and tool logs to \`~/rig/.logs\`, rolls files by size, and keeps logs for seven days by default.
- Use \`context.kv.set(key, value)\` and \`context.kv.get(key)\` for lightweight JSON state stored beside the tool entry file as \`kv.sqlite\`.

Tool SQLite database:
- Add \`setupDb: (db) => { db.migrate(1, "create table", "create table ..."); }\` when a tool needs persistent state.
- Rig stores the database beside the tool entry file as \`index.sqlite\` and runs \`setupDb\` before every command.
- \`db\` is Bun SQLite with \`strict: true\`, WAL mode, and an extra \`db.migrate(version, name, sql)\` helper. Docs: https://bun.com/docs/runtime/sqlite

Command run context:
- \`context.input\` is already validated by the input schema.
- \`context.env\` is already validated by the tool env schema when defined.
- \`context.processEnv\` is the process environment.
- \`context.cwd\` is the current working directory.
- \`context.db\` is available when the tool defines \`setupDb\`.
- \`context.kv\` is always available for lightweight JSON key-value state.
- \`context.log\` is a structured Pino logger for this tool command.
- \`context.rig\` is the toolkit (same as the factory \`rig\` arg, useful for nested tool calls).
- Return a value that matches the output schema.
`;

export class ToolRuntimeCommentSyncService {
  private readonly discovery: ToolDiscoveryService;

  constructor(options: ConfigOptions = {}) {
    this.discovery = new ToolDiscoveryService(options);
  }

  async sync(): Promise<ToolRuntimeCommentSyncResult> {
    const tools = await this.discovery.discover();
    const updates = await Promise.all(
      tools.map(async (tool) => ({
        name: tool.name,
        path: tool.toolPath,
        changed: await this.updateFile(tool.toolPath),
      })),
    );
    return { tools: updates };
  }

  renderPrefix(): string {
    return [
      StartMarker,
      ...RuntimeReference.trimEnd()
        .split("\n")
        .map((line) => (line ? `// ${line}` : "//")),
      EndMarker,
    ].join("\n");
  }

  upsertPrefix(source: string): string {
    const withoutExisting = source.replace(this.managedBlockPattern(), "").trimStart();
    const shebang = withoutExisting.match(/^(#!.*\n)/);
    const prefix = this.renderPrefix();
    const body = shebang ? withoutExisting.slice(shebang[0].length).trimStart() : withoutExisting;
    const next = [prefix, body.trimEnd()].filter(Boolean).join("\n\n");
    return `${shebang?.[0] ?? ""}${next}\n`;
  }

  private async updateFile(path: string): Promise<boolean> {
    const existing = await this.readText(path);
    const next = this.upsertPrefix(existing);
    if (next === existing) return false;
    await this.writeText(path, next);
    return true;
  }

  private async readText(path: string): Promise<string> {
    const bun = this.bunFileApi();
    /* v8 ignore next */
    if (bun) return bun.file(path).text();
    return readFile(path, "utf8");
  }

  private async writeText(path: string, content: string): Promise<void> {
    const bun = this.bunFileApi();
    /* v8 ignore next 4 */
    if (bun) {
      await bun.write(path, content);
      return;
    }
    await writeFile(path, content, "utf8");
  }

  private bunFileApi(): BunFileApi | undefined {
    const candidate = (globalThis as typeof globalThis & { Bun?: Partial<BunFileApi> }).Bun;
    /* v8 ignore next 3 */
    if (typeof candidate?.file === "function" && typeof candidate.write === "function") {
      return candidate as BunFileApi;
    }
    return undefined;
  }

  private managedBlockPattern(): RegExp {
    return new RegExp(
      `${this.escapeRegExp(StartMarker)}[\\s\\S]*?${this.escapeRegExp(EndMarker)}\\n*`,
    );
  }

  private escapeRegExp(value: string): string {
    return value.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
  }
}
